#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

LOCAL_PATH := device/lenovo/malbec

# Soong namespaces
# vendor/lenovo/malbec/Android.bp imports device/lenovo/malbec, so the namespace
# has to be declared here and made visible to the product.
PRODUCT_SOONG_NAMESPACES += \
    $(LOCAL_PATH)

# Proprietary blobs
$(call inherit-product, vendor/lenovo/malbec/malbec-vendor.mk)

# Symlinks that point at runtime locations instead of shipped files, so
# extract-utils cannot generate them. See Android.bp for what each one is for.
PRODUCT_PACKAGES += \
    malbec_wlanmdsp_otaupdate_symlink \
    malbec_wlan_cfg_wcn7750_symlink \
    malbec_wlan_mac_wcn7750_symlink \

# ⚠️ There used to be a CneApp.libvndfwk_detect_jni.qti_vendor_symlink here,
# working around an UnsatisfiedLinkError in CneApp. Session 13 removed CneApp
# itself along with the rest of the cellular stack: CNE is Qualcomm's
# Connectivity Engine, which arbitrates between cellular and Wi-Fi, and this is
# a Wi-Fi-only tablet (ro.baseband=apq, no RIL running, lshal reports zero
# radio/ims interfaces). With the app gone the symlink has nothing to satisfy.

# Generic ramdisk allow list
$(call inherit-product, $(SRC_TARGET_DIR)/product/generic_ramdisk.mk)

# Project ID Quota
$(call inherit-product, $(SRC_TARGET_DIR)/product/emulated_storage.mk)

# Virtual A/B
# Stock enables compression, userspace snapshots, batch writes, io_uring and
# XOR (ro.virtual_ab.compression.xor.enabled=true), so inherit the XOR variant.
# It chains through compression.mk to launch_with_vendor_ramdisk.mk, which is
# where PRODUCT_VIRTUAL_AB_OTA and the vendor ramdisk fsck tools come from.
$(call inherit-product, $(SRC_TARGET_DIR)/product/virtual_ab_ota/compression_with_xor.mk)

# Dalvik vm configs
# 6144 is the largest profile AOSP ships and is the right one for this 8 GB device.
# The "phone" in the name is historical; the profiles are keyed on RAM and density.
$(call inherit-product, frameworks/native/build/phone-xhdpi-6144-dalvik-heap.mk)

# AVF
# Stock ships com.android.virt, so keep parity. Note that VmTerminalApp is
# deliberately NOT included: the hypervisor here is Gunyah, not KVM, /dev/kvm
# does not exist and only protected VMs are supported, so the Terminal's
# non-protected Debian VM cannot start. See PROGRESS.md.
$(call inherit-product, packages/modules/Virtualization/apex/product_packages.mk)

# Qualcomm
# ⚠️ This line is a NO-OP and the story that used to be written here never
# happened. Kept only because it documents the correct intent; delete it if you
# would rather have one less lie in the file.
#
# The old comment claimed the previous value "modem_firmware" produced a dangling
# /vendor/rfs/msm/mpss/readonly/firmware symlink. It cannot have:
# hardware/qcom-caf/common/Android.bp:236-243 offers exactly two branches,
# "firmware" -> /firmware and "firmware_modem" -> /vendor/firmware-modem, with
# `default: "/vendor/firmware_mnt"`. Neither "modem_firmware" NOR "firmware_mnt"
# matches a branch, so both fall to the same default. Setting it changes nothing.
# Verified on the built image: all 84 vendor/rfs/** symlinks are byte-identical
# to the factory ones.
$(call soong_config_set,rfs,mpss_firmware_symlink_target,firmware_mnt)
$(call inherit-product, hardware/qcom-caf/common/common.mk)

# vndservicemanager must be built from source, not carried as a blob.
#
# This one has to be requested explicitly, and the reason is a trap worth
# spelling out. base_vendor.mk does list it -- but at :105-108, under
# PRODUCT_PACKAGES_SHIPPING_API_LEVEL_29, not PRODUCT_PACKAGES. main.mk:1005
# folds that list in only when math_gt_or_eq(29, PRODUCT_SHIPPING_API_LEVEL) is
# true, and this product ships 36 (see PRODUCT_SHIPPING_API_LEVEL below). So
# AOSP contributes nothing here: dropping the blob line WITHOUT this block would
# leave /vendor/bin/vndservicemanager missing entirely, and
# vendor/etc/selinux/vndservice_contexts (generated by system/sepolicy, not a
# blob) names 12 QTI services that must register on /dev/vndbinder --
# display.qservice, vendor.qcom.PeripheralManager, the gnss xtra service, the
# nwmgr service, wfd.native.mm.service and more.
#
# Why it cannot stay a blob: Lenovo's copy is an Android-15 build of
# android::ServiceManager, and /vendor/lib64/libbinder.so is built from this
# tree (Android 16). AOSP inserted getService2 and checkService2 into
# IServiceManager *before* addService, so every vtable slot from addService on
# is shifted by two. BnServiceManager::onTransact then calls the wrong virtual
# with the wrong argument types -- observed as both
# "Check failed: outList->empty()" in listServices and a null deref in
# IInterface::asBinder. Since Android 15 removed the VNDK, libbinder is compiled
# from the current tree into /vendor and its C++/AIDL ABI is explicitly
# unstable, so a vendor binary that *implements* an AOSP Bn* interface has to be
# rebuilt with the tree. vndservicemanager is the only blob on this device that
# does. Every symbol still resolved, so no link-time check could have caught it.
#
# This mattered more than a single dead service: vndservicemanager.rc carries
# "onrestart class_restart main / hal / early_hal" (byte-identical to AOSP's --
# Lenovo never touched the file), and it is the only .rc in all 138 vendor init
# files that cascades. One crash restarted the whole userspace every ~5 s, which
# is why the first flash never reached the launcher.
#
# vndservice and the .rc come along for free:
# frameworks/native/cmds/servicemanager/Android.bp:80-93 has
# required: ["vndservice"] and init_rc: ["vndservicemanager.rc"].
PRODUCT_PACKAGES += \
    vndservicemanager

# QTI HALs built from source rather than carried as blobs, matching onyx.
# The sources are in this tree (hardware/qcom-caf, vendor/qcom/opensource), so
# the stock binaries would only shadow them — and being compiled against an
# older AIDL version, the resulting module ends up depending on two versions of
# the same interface at once, which Soong rejects:
#
#   android.hardware.health-service.qti: depends on multiple versions of the
#   same aidl_interface: android.hardware.health-V3-ndk-source,
#   android.hardware.health-V4-ndk-source
#
# proprietary-files.txt excludes all of them.
# ⚠️ This list was once missing more than half its entries, and the way it went
# missing is subtle enough to be worth writing down. The classifier that
# generates proprietary-files.txt had a rule: "the module name is defined in an
# enabled QTI soong namespace -> this blob does not need extracting". The rule
# is not wrong; what was wrong is that it never checked whether that source
# module actually entered PRODUCT_PACKAGES. Defined != built.
# So composer, boot control, thermal and the audio HAL implementation libraries
# fell between the two: the blob was dropped and nothing installed the source
# either. With no composer, SurfaceFlinger does not start and the device is a
# black screen.
# work/scripts/24-blob-reconcile.py now does the reverse reconciliation (present
# in stock, absent from the image = a gap), so this class cannot go silently
# missing again.
# ⚠️ android.hardware.thermal-service.qti WAS in this list and is now a BLOB.
# It is the one QTI HAL where "the source is in the tree, so build it" is
# provably the wrong answer for this board, and the reason generalises to every
# other entry here: these HALs carry a per-SoC table written against Qualcomm's
# REFERENCE board, and Lenovo's board is not it.
#
# thermalConfig.cpp:2487-2500 maps SKIN for soc_id 694 to thermal zone
# `sys-therm-3`, which this board does not populate — so the source build ships
# with NO skin temperature, which takes PowerManager.getThermalHeadroom(),
# HardwarePropertiesManager's skin reading and every skin-driven
# THERMAL_STATUS_* with it. Stock's blob maps SKIN to `quiet-therm`, which
# exists. Full derivation, the same-instant measurement that identifies the
# zone, the ABI analysis and the on-device proof are on the entry in
# proprietary-files.txt.
#
# The other five stay on source. Checked so far: the USB HAL's `dumpsys usb`
# port_manager block is field-for-field identical to stock's, so its table is
# right for this board. health / usb.gadget / qspa are unverified — if one of
# them turns out to have the same shape, the answer is the same one.
PRODUCT_PACKAGES += \
    android.hardware.health-service.qti \
    android.hardware.usb-service.qti \
    android.hardware.usb.gadget-service.qti \
    audiohalservice.qti \
    vendor.qti.qspa-service

# Display: the whole QTI display stack is a BLOB. Do not move it back to source.
#
# ⚠️ This section used to say "the entire display stack is built from source in
# this tree ... there is not one blob, so the composer has to come from source
# too". That premise was FALSE, and it is what made session 11 file the correct
# answer under "already ruled out" and lose a whole round:
#
#   · libsdmextension.so (2.3 MB) was always a blob, and it is the most tightly
#     coupled member of the cluster. It is brought in by dlopen
#     (core_impl.cpp:80) and appears in NO DT_NEEDED, so a link-graph search
#     cannot find it. That is exactly why it was missed.
#   · OPEN-ISSUES #9's "exclusion 3" claimed onyx also builds this display stack
#     from source. It does not: onyx treats the WHOLE cluster as blobs —
#     proprietary-files.txt:2261,2274-2296,2320, with device.mk:130-143
#     installing only the peripheral modules.
#
# Stock's SDM is a private Lenovo/Motorola fork (SetMotoColor, SetRGBASplit,
# SetMotoPAHsic — zero hits in the public CAF sources), sdm::DisplayBase's vtable
# has TWO MORE SLOTS than this tree's source builds (161 vs 159), and its data
# members are 48 bytes larger. The fork is not published and libsdmextension has
# no source at all, so building this half from source CANNOT be structurally
# correct. The full criteria and measurements are in the Display section of
# proprietary-files.txt.
#
# The stock ROM is the existence proof: fingerprint TB390FU:16/... is an
# Android 16 framework over a 202404-frozen vendor, the same Treble
# configuration as this tree.
#
# The stock composer binary links vendor.qti.hardware.display.composer3-V1-ndk.so
# while this tree installs only V3 by default — measured, it is the single
# library missing from the DT_NEEDED closure of those 28 files.
#
# Supplying it looks simple and has two dead ends, both hit for real. Written
# down so nobody walks them again:
#
#   ✗ Plain `PRODUCT_PACKAGES += vendor.qti.hardware.display.composer3-V1-ndk`
#     fails soong bootstrap. In versions_with_info at
#     commonsys-intf/display/aidl/composer3/Android.bp:22-25, version 1 imports
#     android.hardware.graphics.composer3-**V4**, while the composer blob itself
#     links composer3-**V3**-ndk.so directly. Two versions of one aidl_interface
#     in a single dependency graph, which Soong rejects.
#     (Stock's V1 was compiled against V3: readelf -d it and NEEDED says
#     composer3-V3-ndk. The V1 -> V4 import in the tree is a later upstream
#     change and does not match the stock binary.)
#
#   ✗ Extracting stock's .so as a blob (even with ;MODULE_SUFFIX=_vendor) gives
#     ninja: multiple rules generate .../symbols/vendor/lib64/
#     vendor.qti.hardware.display.composer3-V1-ndk.so. Renaming does not escape
#     it: ;MODULE_SUFFIX changes the MODULE name only, the stem is unchanged, so
#     the install path is still the same one — and the source aidl module ALREADY
#     has an install rule pointing at that path. (It was simply not in
#     PRODUCT_PACKAGES, so it never reached the image; ninja's dupbuild check
#     looks at rules, not at what gets packaged.) This is the counterexample to
#     the line in proprietary-files.txt saying "renaming only works when the tree
#     installs nothing at that path".
#
# The answer is two steps: tag the composer blob ;DISABLE_DEPS to cut that aidl
# dependency edge (which removes the conflict), then explicitly install the
# source-built V1 vendor variant. The `.vendor` suffix is the correct way to
# install the vendor variant of a vendor_available module — QTI writes it the
# same way in
# commonsys-intf/display/config/display-interfaces-product.mk:40-43.
#
# ⚠️ `;DISABLE_DEPS` turns off shared_libs generation AND check_elf_file, so the
# build goes green while the image is missing libraries — the exact failure mode
# OPEN-ISSUES #3 documents. The safety net is work/scripts/33-blob-linkcheck.py,
# and it earned its keep here: with only V1 listed it reported
#
#   [vendor] android.hardware.graphics.composer3-V3-ndk.so   nowhere in the product
#   [vendor] vendor.qti.hardware.display.aiqe-V2-ndk.so      nowhere in the product
#   vendor/bin/hw/vendor.qti.hardware.display.composer-service  6 unresolved symbols
#
# Both had been installed only as a side effect of the SOURCE composer depending
# on them; dropping it took them with it. Run 33 after ANY ;DISABLE_DEPS change.
PRODUCT_PACKAGES += \
    vendor.qti.hardware.display.composer3-V1-ndk.vendor \
    vendor.qti.hardware.display.aiqe-V2-ndk.vendor \
    android.hardware.graphics.composer3-V3-ndk.vendor

# ⚠️ libgpu_tonemapper is the ONE member of the display cluster that stays on
# SOURCE, and it must. Blobbing it re-introduced the very bug that got the XR
# stack deleted:
#
#   work/scripts/37-layout-skew.py
#     ✗ vendor/lib64/libgpu_tonemapper.so: android::GraphicBuffer allocates 256 < A16 3376
#
# The factory copy is an Android-15 build that does operator new(256) for a class
# A16 grew to 3376 bytes (frameworks/native df868baf2a added mDependencyMonitor).
# It is reached whenever HDR tone mapping runs, so it would corrupt the heap in
# normal use, not in some corner.
#
# Source is safe for this one specifically, and the criterion is not a guess:
# the full exported-symbol-set diff of every source-built vendor library against
# its factory counterpart found the Moto fork in exactly five libraries —
# libsdmcore, libsdmclient, libsdmdal, snapalloc-impl, libgrallocutils.
# libgpu_tonemapper has ZERO factory-only symbols, i.e. it is not forked, so the
# tree build and the factory build are the same code.
#
# Nothing pulls it in automatically any more: the composer that used to depend on
# it is now a blob carrying ;DISABLE_DEPS, so it has to be named here.
PRODUCT_PACKAGES += \
    libgpu_tonemapper

# Audio HAL implementation libraries — these come from BLOBS, not source.
#
# audiohalservice.qti is only a shell; the real implementation is the three .so
# files it dlopens. dlopen produces no build dependency, so they have to be named
# explicitly or the service starts with no HAL behind it. Their `required:` pulls
# in the two VINTF fragments manifest_audiocorehal_default.xml and
# audioeffectservice_qti.xml — without those the framework's FactoryHal, which
# looks HALs up with AServiceManager_isDeclared, concludes the device has no
# audio HAL at all.
#
# ⚠️ Source-vs-blob has to be pinned down HERE and cannot be left for a
# convergence loop to discover. Each choice is self-consistent, but mixing them
# oscillates: the generated malbec-vendor.mk puts libaudiocorehal.default into
# PRODUCT_PACKAGES, that name resolves to the in-tree source module when it is
# not renamed, so the tree installs the path, the criterion decides the blob is
# redundant and drops it — and then nothing provides it and the next round puts
# it back. Measured: three round trips.
#
# ⚠️ An earlier version chose "build from source" here, on the grounds that the
# DT_NEEDED of the three stock .so files links several versions of the same AIDL
# interface at once and replace_needed cannot fix that. The observation was
# right and the conclusion was wrong — the answer is ;DISABLE_DEPS plus
# co-installing the older interface, which is what onyx does. Source has two
# costs that argument missed:
#
#   1. It loses the Awinic smart amplifiers. The stock libar-pal.so exports 44
#      aw_ar_dsp_* / aw_ar_kmsg_* / aw_audioreach_* symbols and the CAF sources
#      contain zero Awinic code. Those amplifiers are this device's speakers:
#      aw882xx_dlkm is loaded (refcount 4), and this tree ships their calibration
#      data (vendor/firmware/aw882xx_acf.bin) and calibration tool
#      (vendor/bin/aw882xx_cali) — data and tool present, the API that consumes
#      them gone. What would be lost is not only sound quality: excursion and
#      temperature protection live in that same API.
#      Generalising the check to all 330 libraries that this tree builds from
#      source and stock also ships, scanning for OEM-patch signature symbols,
#      only libar-pal.so is affected — so audio is the only subsystem that has to
#      go back to blobs; the display stack is clean.
#
#   2. It does not compile. hardware/qcom-caf/sm8750/audio/pal has 8 objects that
#      fail -Wformat in this tree (Bluetooth.cpp, ResourceManager.cpp,
#      SessionAlsa*.cpp, SoundTriggerEngineGsl.cpp, StreamHaptics.cpp,
#      HapticsDevProtection.cpp). `m nothing` cannot see this layer, and the
#      previous round's `mka bacon` died at 9%, before reaching it.
#
# So PAL, AGM, graphservices, the three HAL implementation libraries and st-hal
# all go back to blobs, picked up by proprietary-files.txt under "the tree does
# not install this path", with conflicts handled by ;DISABLE_DEPS (see ENTRY_TAGS
# in work/scripts/12-gen-proprietary-files.py).
#
# audiohalservice.qti stays on source: it is only a shell, it dlopens the three
# implementation libraries, it does not link PAL, it compiles, and its `init_rc:`
# brings vendor/etc/init/audiohalservice_qti.rc with it.
# libsoundtriggerhal.qti must be a blob — st-hal-ar/Android.bp:37 links libar-pal
# explicitly. onyx splits it exactly the same way.

# ★★ Without this line the device never reaches the launcher ★★
#
# properties/system_ext.prop:16 sets
# ro.audio.ihaladaptervendorextension_enabled=true (for a reason that is stated
# there and is correct), but the implementing service was never installed.
# Property set, implementation absent — the "declared but not implemented" class
# again, and in audio that class is FATAL rather than merely a missing feature:
#
#   frameworks/av/media/libaudiohal/impl/DevicesFactoryHalAidl.cpp:123-136
#     if (property_get_bool("ro.audio.ihaladaptervendorextension_enabled", false)) {
#         ... AServiceManager_waitForService(".../IHalAdapterVendorExtension/default")
#     } else { mVendorExt = nullptr; }
#
#   waitForService waits FOREVER. The measured chain is:
#     audioserver: AudioPolicyService::onFirstRef -> createAudioPolicyManager
#       -> AudioFlinger::getAudioPolicyConfig -> loadHwModule_ll
#       -> DeviceHalAidl::initCheck -> parseAndGetVendorParameters
#       -> HalAdapterVendorExtensionWrapper::getService -> stuck
#   so audioserver never registers IAudioFlingerService, and system_server hangs
#   the same way in
#     AudioService.<init> -> readUserRestrictions -> setMicrophoneMuteNoCallerCheck
#     -> AudioSystem::isMicrophoneMuted -> getService<IAudioFlingerService>
#   sys.boot_completed never appears and the boot animation spins forever.
#   servicemanager printing "could not be found trying to start it as a lazy AIDL
#   service ... but was unable to" once a second is the symptom, not the cause.
#
# This tree builds the service itself
# (vendor/qcom/opensource/commonsys/audio/hal_adapter/) and its .rc carries
# `interface aidl android.media.audio.IHalAdapterVendorExtension/default` — that
# line is what lets servicemanager lazy-start it.
# The stock image ships only system_ext/lib64/libaudiohalvendorextn.so and
# neither the binary nor the .rc (it is not among the 29 files in
# system_ext/bin), so stock is not a usable reference here.
# onyx gets it right: device.mk:70 installs the service and
# properties/system_ext.prop:2 sets the property — the two must come as a pair.
PRODUCT_PACKAGES += \
    qtiaudiohalvendorextn

# ★★ Load-bearing — do not trim ★★
# This block, and the display one further up, exist to COMPENSATE for
# ;DISABLE_DEPS. What ;DISABLE_DEPS turns off is Soong's dependency generation,
# which means Soong will neither install these libraries for us nor complain
# about them. Deleting any line here produces a dlopen failure after boot while
# `m nothing`, a full `m` and check_elf_file all stay silent — it is completely
# invisible at build time.
# To check whether the set is still complete, run
# `python3 work/scripts/33-blob-linkcheck.py` (it solves per linker namespace
# rather than taking a union across partitions).
#
# ;DISABLE_DEPS keeps the blobs out of Soong's dependency graph, but at runtime
# they still have to find in /vendor/lib64 the exact interface version they were
# linked against. This tree resolves to a newer version, so the older one has to
# be co-installed explicitly. The version numbers come from readelf -d on each
# stock binary, not from guesswork.
# Multiple versions coexisting is supported by design, and this tree already has
# a precedent: android.media.audio.common.types V2 and V4 are both installed
# today.
PRODUCT_PACKAGES += \
    android.hardware.audio.common-V3-ndk.vendor \
    android.hardware.audio.core-V2-ndk.vendor \
    android.hardware.audio.core.sounddose-V1-ndk.vendor \
    android.hardware.audio.core.sounddose-V2-ndk.vendor \
    android.hardware.audio.effect-V2-ndk.vendor \
    android.hardware.bluetooth.audio-V3-ndk.vendor \
    android.hardware.bluetooth.audio-V4-ndk.vendor \
    android.hardware.drm-V1-ndk.vendor \
    android.hardware.health-V1-ndk.vendor \
    android.media.audio.common.types-V3-ndk.vendor \
    vendor.qti.hardware.paleventnotifier-V2-ndk.vendor

# Vendor variants of the AOSP support libraries the stock audio blobs depend on.
# onyx lists the same set.
#
# ⚠️ libaudioutils_shim has NO build-time dependency edge, and the asymmetry with
# libinput_shim is invisible. extract-files.py adds it to
# libaudioserviceexampleimpl.so's DT_NEEDED, but that blob carries ;DISABLE_DEPS,
# so extract_utils/makefiles.py:135-137 sets gen_deps=False and check_elf=False
# and the generated Android.bp entry has no shared_libs at all. This
# PRODUCT_PACKAGES line is the ONLY thing installing it.
#
# Deleting the line goes green and then fails at runtime: the blob carries
# BIND_NOW, so an unresolved symbol makes dlopen fail outright, its consumer is
# mandatory="true" in vendor_audio_interfaces.xml, and Service.cpp:53-77 retries
# ten times and then LOG_ALWAYS_FATALs — audiohalservice.qti in an init respawn
# loop. work/scripts/33-blob-linkcheck.py is the only guard.
#
# libinput_shim is NOT ;DISABLE_DEPS and does get a real edge, which is why it
# looks like this line is equally safe to remove. It is not.
PRODUCT_PACKAGES += \
    libalsautilsv2.vendor \
    libaudioaidlcommon.vendor \
    libmediautils_vendor.vendor \
    libmemunreachable.vendor \
    libaudioutils_shim

# ⚠️ Dolby Atmos is REMOVED — no app, no effects, no overlay.
#
# Music playback stuttered continuously whenever Dolby Atmos was on and was
# clean the moment it was switched off. Measured on the device, same track,
# same volume, same thread (AudioOut_15, deep buffer -> speaker, 40 ms period):
#
#                    process time      jitter min/max    delayed   underruns
#   Dolby on         2.91 ms / 18.0    -36.6 / +23.4        0          0
#   Dolby off        0.48 ms /  6.1    -37.1 / +26.2        0          0
#
# Nothing is late — zero delayed writes, zero underruns, and the jitter in the
# bad case equals the good one. The DAP corrupts the stream in place rather
# than arriving late, which is why every counter stayed clean while it was
# audibly broken. Four hypotheses were tested and disproven (CPU starvation,
# video-decode contention, the tinyxml2 sizeof break, and the app re-writing
# effect parameters); the amplifiers were cleared as well. The root cause
# inside libswdapaidl.so was not found, and the owner chose removal over
# further hunting — which is also this tree's standing rule: shipping a
# feature guaranteed to fail is worse than not shipping it. The full
# derivation, including the four dead hypotheses so nobody re-runs them, is on
# the audio_effects_config.xml fixup in extract-files.py.
#
# What went: libswdapaidl.so, libswgamedapaidl.so, libdlbvolaidl.so,
# libdlbpreg.so (5.9 MB), their declarations in audio_effects_config.xml, the
# co.aospa.dolby app and DolbyAtmosOverlayMalbec.
#
# What deliberately STAYED, because it is not the same thing:
#   * The AC3 / E-AC3 / AC4 decoders. A separate stack that merely shares
#     libdmshal.so with the effects; AOSP ships no replacement, so removing
#     them would cost every AC3 soundtrack for no reason connected to the bug.
#   * Dolby Vision (dvs-aidl-service, dolby_vision.cfg, libdolbyeglcore.so).
#     That is video HDR, which this device is required to support.

# ── MalbecParts: the device's own settings surface ──────────────────────────
#
# Same shape as the DolbyAtmos decision above, for the same reason: this device
# has hardware AOSP has no UI for, and the answer is one small platform-signed
# app injected through Settings' own extension points, not a ported ZUI app.
#
# What it covers, and why each one needs an app at all:
#
#   Pen buttons        The five side-button gestures reach the framework as
#                      F13..F17 (keylayout/Vendor_17ef_Product_617f.kl). AOSP has
#                      the binding mechanism — InputManager#addCustomInputGesture,
#                      per-user and persisted by the framework itself — but the
#                      only UI that drives it is the touchpad three-finger-tap
#                      page. Nothing binds a single key.
#   Keyboard app keys  Same mechanism, F19/F20. ⚠️ These were mapped to
#                      MACRO_1/MACRO_2 until session 16, which is
#                      *structurally* dead: PhoneWindowManager.java:5124-5128
#                      strips MACRO before the gesture layer ever runs. The two
#                      keys did nothing at all.
#   Out-of-range alert The stock feature is much smaller than its name: HID link
#                      dropped, not locally initiated, did not come back. All of
#                      it is public Bluetooth API.
#   Touch mode         The panel rate and the touch controller's report rate are
#                      one hardware knob with two coherent settings, and the
#                      owner asked for a manual switch rather than automatic
#                      switching. Also carries the ContentObserver that stops
#                      Settings > Display > Refresh rate from silently killing
#                      the stylus by choosing 144 Hz.
#
# It adds NO sepolicy of its own: it runs as system_app via
# sharedUserId=android.uid.system, and the one vendor node it needs written is
# written by init.malbec.rc off a persist.sys.* property instead, which
# system_app can already set. See app/MalbecParts/README.md.
#
# ⚠️ It is a priv-app, so every signature|privileged permission it requests must
# also be in /system_ext/etc/permissions/. That allowlist is pulled in by the
# app module's `required:` — do not add it here as well, and do not remove it.
# Shipping the app without it is not a warning: system_server throws in
# systemReady() and the device sits on the boot animation forever. It did, once.
PRODUCT_PACKAGES += \
    MalbecParts

# Miracast: the compat shim that gives libwfdnative.so the pre-Android-16
# MotionEvent::initialize symbol. See the blob_fixup in extract-files.py for why
# this is the correct fix rather than ;DISABLE_CHECKELF. Installs to
# /system_ext/lib64, the same namespace as its consumer.
PRODUCT_PACKAGES += \
    libinput_shim

# ── Sonames that ;DISABLE_DEPS blobs need and nothing in the tree provides ──
#
# This entire class is INVISIBLE at build time: ;DISABLE_DEPS turns off both
# shared_libs generation and check_elf_file, so Soong neither builds the
# dependency nor complains. `m nothing` and a full `m` go green and the dlopen
# fails after boot.
#
# Session 7 located them with one exhaustive scan (3370 ELFs, 27346 DT_NEEDED
# edges, solved per LINKER NAMESPACE rather than by taking a union across
# partitions): 20 real gaps. Seven of those were a new category — the file IS in
# the image but cannot cross the vendor/system namespace boundary. Android 16 has
# no VNDK, so a /vendor binary sees only /odm/lib64, /vendor/lib64{,/hw,/egl} and
# the 26 entries in system/etc/llndk.libraries.txt. A library like
# android.hardware.health@1.0.so, plainly present in /system/lib64, therefore does
# not exist as far as a vendor consumer is concerned, and the .vendor variant has
# to be installed.
#
# How they are split (the criterion is WHO CONSUMES IT, not what the library
# looks like):
#   · Frozen stable interfaces (HIDL @x.y, AIDL -Vn-ndk) -> from the tree. The ABI
#     is defined by the frozen interface, so the tree build and the stock build
#     are symbol-for-symbol equivalent; each one here was checked by matching
#     consumer undefined symbols against provider exports.
#   · An ordinary C++ library that is not an interface, whose consumer is a stock
#     blob -> from the blob set (in proprietary-files.txt), because that consumer
#     is an Android 15 binary and internal ABI is not guaranteed across a major
#     version. libaudioserviceexampleimpl, libaudioplatformconverter.qti,
#     libnbaio_mono, qti-audio-types-aidl-V1-ndk and the six soundfx AIDL effect
#     libraries are all this case.
PRODUCT_PACKAGES += \
    android.hardware.bluetooth.audio@2.0.vendor \
    android.hardware.bluetooth.audio@2.1.vendor \
    android.hardware.health@1.0.vendor \
    android.hardware.health@2.0.vendor \
    android.hardware.health@2.1.vendor \
    android.hardware.power@1.0.vendor \
    android.hardware.power@1.1.vendor \
    android.hardware.power@1.2.vendor \
    android.hardware.soundtrigger3-V1-ndk.vendor \
    android.hardware.thermal@1.0.vendor \
    android.hardware.thermal@2.0.vendor \
    android.media.soundtrigger.types-V1-ndk.vendor \
    com.dsi.ant@1.0.vendor \
    libaudio_aidl_conversion_common_ndk.vendor \
    libflatbuffers-cpp.vendor \
    libusbhost.vendor \
    libwfdaac_vendor \
    qti-audio-types-aidl-V1-ndk.vendor \
    vendor.qti.hardware.bluetooth.audio-V1-ndk.vendor \
    vendor.qti.hardware.display.allocator@4.0.vendor

# These two VINTF fragments come from source rather than from the blob set. They
# used to arrive as `required:` of libaudiocorehal.default / libaudioeffecthal.qti;
# once those implementation libraries went back to blobs nothing carried them any
# more, and extracting the stock copies collides with the source modules by name
# (both are named prebuilt_etc, and ;MODULE_SUFFIX= is silently ineffective on
# prebuilt_etc):
#   module "audioeffectservice_qti.xml": found in multiple
#   namespaces(hardware/qcom-caf/sm8750 and vendor/lenovo/malbec)
# The two copies were compared field by field: the declarations are identical and
# only the comments differ, so either would do — taking the source one avoids the
# name collision.
PRODUCT_PACKAGES += \
    manifest_audiocorehal_default.xml \
    audioeffectservice_qti.xml

# libaudioeffecthal.qti is built from source rather than extracted, and this is
# a deliberate exception to the "audio implementation libraries are blobs" rule
# two blocks up. That rule exists because the factory libar-pal.so carries 44
# Awinic smart-PA symbols the source tree has none of -- which is about
# libar-pal and libaudiocorehal, not about the effects library.
#
# The factory libaudioeffecthal.qti.so cannot be used on Android 16 at all. It
# memsets exactly 0x308 (776) bytes of stack and constructs a
# tinyxml2::XMLDocument there, but AOSP's tinyxml2 11.0.0 uprev grew that object
# to 0x370 (880). The extra 104 bytes land on the callee-saved register area and
# zero the TPIDR_EL0 copy used for the stack guard, so the next instruction
# (ldr x8,[x22,#0x28]) faults on address 0x28 -- esr 0x92000005, exactly what
# the first-flash tombstone shows. Every attempt to ship the 776-byte library
# instead is blocked by Android 16; the three measured refusals are documented
# at the top of proprietary-files.txt.
#
# The source build is compiled against the v11 header, so it reserves the right
# size and the bug cannot occur.
PRODUCT_PACKAGES += \
    libaudioeffecthal.qti

# IPA (data-path acceleration)
#
# The two configuration files have to be listed explicitly. ipacm's Android.bp has
# no `required:` carrying them, and "the module is defined" != "this product
# builds it" — the lesson recorded in PROGRESS.md section 3. The last full build
# installed /vendor/bin/ipacm with no IPACM_*.xml at all, while ipacm.rc:42 does
# `copy /vendor/etc/IPACM_Filter_cfg.xml`.
#
# ⚠️ Taken from the tree rather than extracted from stock, for a measured reason:
# stock's IPACM_cfg.xml has NO wlan0/wlan1/wlan2/wlan3/wigig0 Iface entries and
# the sm8750 copy in the tree does — all 25 lines of difference are exactly those.
# This is a Wi-Fi-only tablet, and the wlan interfaces are precisely what IPA
# offload would use; stock's copy was trimmed by Lenovo for their own SKU.
# IPACM_Filter_cfg.xml is byte-identical on both sides and follows the tree to
# keep the pair together. The ipacm binary itself is also built from
# hardware/qcom-caf/sm8750, so configuration and binary share a source.
PRODUCT_PACKAGES += \
    ipacm \
    IPACM_cfg.xml \
    IPACM_Filter_cfg.xml

# Sensors
# The multihal service and its NDK bridge are AOSP's; only the sub-HALs listed
# in the stock /vendor/etc/sensors/hals.conf are device specific, and those stay
# as blobs. onyx does the same — it extracts no sensors service blob at all.
PRODUCT_PACKAGES += \
    android.hardware.sensors-service.multihal \
    sensors.dynamic_sensor_hal

# DRM
# clearkey is AOSP's reference plugin, not a device blob.
PRODUCT_PACKAGES += \
    android.hardware.drm-service.clearkey

# Device characteristics
# Not set anywhere in the inherited tablet config, but stock reports
# ro.build.characteristics=tablet and resource selection depends on it.
PRODUCT_CHARACTERISTICS := tablet

# Partitions
# BoardConfig.mk describes the super partition and its group, but the product
# side has to opt in as well: PRODUCT_BUILD_SUPER_PARTITION defaults to this, and
# without it no super.img is assembled.
PRODUCT_USE_DYNAMIC_PARTITIONS := true

# fstab.qcom mounts /vendor/firmware_mnt, /vendor/dsp and /vendor/bt_firmware.
# Stock ships those three as empty directories and proprietary-files.txt cannot
# carry an empty directory, so nothing would create them and all three mounts
# would fail. These modules exist for exactly that
# (hardware/qcom-caf/common/Android.bp); onyx pulls in the same set.
PRODUCT_PACKAGES += \
    vendor_bt_firmware_mountpoint \
    vendor_dsp_mountpoint \
    vendor_firmware_mnt_mountpoint

# A/B
# AB_OTA_UPDATER is set in BoardConfig.mk, but the updater itself is a product
# package. Without these three the build still produces an OTA zip and the device
# has nothing able to apply it.
#
# android.hardware.boot-service.qti is equally required, and it fails earlier than
# the three above: without IBootControl, update_engine cannot mark the current
# slot successful, and once the bootloader's retry counter runs out it rolls back
# to the other slot.
# android.hardware.boot carries no optional="true" in
# compatibility_matrix.202404.xml — it is mandatory. The recovery variant is for
# sideload.
PRODUCT_PACKAGES += \
    android.hardware.boot-service.qti \
    android.hardware.boot-service.qti.recovery \
    update_engine \
    update_engine_sideload \
    update_verifier

AB_OTA_POSTINSTALL_CONFIG += \
    RUN_POSTINSTALL_system=true \
    POSTINSTALL_PATH_system=system/bin/otapreopt_script \
    FILESYSTEM_TYPE_system=ext4 \
    POSTINSTALL_OPTIONAL_system=true

AB_OTA_POSTINSTALL_CONFIG += \
    RUN_POSTINSTALL_vendor=true \
    POSTINSTALL_PATH_vendor=bin/checkpoint_gc \
    FILESYSTEM_TYPE_vendor=ext4 \
    POSTINSTALL_OPTIONAL_vendor=true

PRODUCT_PACKAGES += \
    otapreopt_script \
    checkpoint_gc

# API
# Both values are what the device actually shipped with, read off the stock
# vendor build.prop: ro.board.first_api_level / ro.board.api_level = 202404 and
# ro.product.first_api_level = 36.
#
# BOARD_SHIPPING_API_LEVEL is the one that matters for booting. It is the vendor
# API surface this device froze at (Android 15, VINTF target-level 202404) while
# the framework side is Android 16, which is the Treble GRF arrangement this
# port depends on. Declare it too low or too high and the VINTF compatibility
# check between the framework matrix and the vendor manifest fails.
#
# PRODUCT_SHIPPING_API_LEVEL is 36 rather than onyx's 35 simply because this
# tablet launched on Android 16 and onyx launched on 15.
#
# BOARD_API_LEVEL is deliberately absent: the release config sets it from
# RELEASE_BOARD_API_LEVEL and build/make/core/board_config.mk errors out if a
# device tree assigns it.
BOARD_SHIPPING_API_LEVEL := 202404
PRODUCT_SHIPPING_API_LEVEL := 36

# ── Hardware feature declarations ───────────────────────────────────────────
#
# ★ Every one of these arrived only through proprietary-files.txt until session
# 25, and that was the largest silent-failure surface left in this port
# (work/OPEN-ISSUES.md #64, previously the standing #58 item). A feature XML is
# not a driver: nothing links it, nothing loads it, no check_elf_file looks at
# it. Drop one and the build stays green while PackageManager simply stops
# advertising the feature. `handheld_core_hardware.xml` alone carries
# android.hardware.camera, android.software.home_screen,
# android.software.input_methods and android.software.secure_lock_screen — a
# re-extraction that lost it would ship a tablet with no launcher, no keyboard
# and no lock screen, and the only symptom would be the device.
#
# So they are declared here, from their upstream sources, and removed from the
# blob list in the same change. 34 of the 36 files under
# /vendor/etc/permissions/ were verified byte-identical to a file that already
# exists in this checkout (session 25 diffed each one against
# frameworks/native/data/etc/); the two that are not have device-tree copies in
# configs/permissions/ with the derivation written in their headers.
#
# ⚠️ The destination is $(TARGET_COPY_OUT_VENDOR), matching where stock put them
# and what build/make/target/product/full_base_telephony.mk does. These describe
# hardware, so they belong on the hardware partition.
#
# ⚠️ Three files at that path stay blobs, correctly: privapp-permissions-qti-vendor.xml
# and vendor.qti.{dcf,qva}.xml grant privileged permissions to Qualcomm packages
# and have no upstream source. features_com.android.virt.xml was never a blob —
# packages/modules/Virtualization builds it.
#
# ⚠️ The six sensor files are FLATTENED out of the SKU subdirectory stock used.
# SystemConfig.java:109,709 reads /vendor/etc/permissions/sku_$(ro.boot.product.vendor.sku)/
# and stock ships them under sku_tuna/, because Lenovo's one vendor image serves
# several SoC SKUs. We build for exactly one, so the indirection buys nothing and
# costs a dependency: if that bootloader property ever read anything but `tuna`,
# gyroscope, light and step-counter would vanish from pm list features with no
# other symptom. At the top level they are unconditional.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/permissions/handheld_core_hardware.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/handheld_core_hardware.xml \
    $(LOCAL_PATH)/configs/permissions/android.hardware.hardware_keystore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.hardware_keystore.xml

# Audio: low_latency and pro are CDD claims about the audio stack, both of which
# stock makes and the smart-amp/USB-C stack here supports.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.audio.low_latency.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.audio.low_latency.xml \
    frameworks/native/data/etc/android.hardware.audio.pro.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.audio.pro.xml \
    frameworks/native/data/etc/android.software.midi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.midi.xml

# Camera. flash-autofocus implies android.hardware.camera, so the rear camera is
# declared here rather than by handheld_core_hardware.xml's bare `camera` line.
# `full` is the FULL hardware level, `raw` is DNG capture, `concurrent` is both
# cameras streaming at once — all three verified against
# `dumpsys media.camera`, which reports 2 devices at level `full`.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.camera.concurrent.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.concurrent.xml \
    frameworks/native/data/etc/android.hardware.camera.flash-autofocus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.flash-autofocus.xml \
    frameworks/native/data/etc/android.hardware.camera.front.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.front.xml \
    frameworks/native/data/etc/android.hardware.camera.full.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.full.xml \
    frameworks/native/data/etc/android.hardware.camera.raw.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.raw.xml

# Connectivity. ⚠️ There is deliberately no android.hardware.telephony*, no
# android.hardware.nfc and no android.hardware.location.gps here: TB390FU is
# Wi-Fi only, has no NFC controller, and has no GNSS receiver — `pm list
# features` on stock advertises none of the three either.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.bluetooth.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.bluetooth.xml \
    frameworks/native/data/etc/android.hardware.bluetooth_le.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.bluetooth_le.xml \
    frameworks/native/data/etc/android.hardware.wifi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.xml \
    frameworks/native/data/etc/android.hardware.wifi.aware.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.aware.xml \
    frameworks/native/data/etc/android.hardware.wifi.direct.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.direct.xml \
    frameworks/native/data/etc/android.hardware.wifi.passpoint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.passpoint.xml \
    frameworks/native/data/etc/android.hardware.location.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.location.xml \
    frameworks/native/data/etc/android.software.ipsec_tunnels.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.ipsec_tunnels.xml \
    frameworks/native/data/etc/android.hardware.usb.accessory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.accessory.xml \
    frameworks/native/data/etc/android.hardware.usb.host.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.host.xml

# Input. jazzhand is 5-or-more independently tracked pointers, and it implies
# both weaker multitouch features. AOSP's own comment says to include exactly one
# of the three, so this is the only touchscreen file here.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml

# Sensors — flattened out of stock's sku_tuna/ (see the note above).
# ⚠️ No android.hardware.sensor.compass and no android.hardware.sensor.proximity:
# `dumpsys sensorservice` lists 36 hardware sensors on this unit and neither a
# magnetic_field nor a proximity type is among them. No barometer either.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.sensor.accelerometer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.accelerometer.xml \
    frameworks/native/data/etc/android.hardware.sensor.gyroscope.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.gyroscope.xml \
    frameworks/native/data/etc/android.hardware.sensor.light.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.light.xml \
    frameworks/native/data/etc/android.hardware.sensor.stepcounter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.stepcounter.xml \
    frameworks/native/data/etc/android.hardware.sensor.stepdetector.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.stepdetector.xml \
    frameworks/native/data/etc/android.hardware.sensor.dynamic.head_tracker.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.dynamic.head_tracker.xml

# Biometrics — face only. There is no fingerprint reader on this tablet, and
# `android.hardware.fingerprint` is correspondingly absent.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.biometrics.face.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.biometrics.face.xml

# Graphics. The two deqp levels are 132645633 = 0x07E80301 = the 2024-03-01 test
# list, so the source files are the -2024-03-01 variants.
#
# ⚠️ Stock's own copies of these two are named for 2023-03-01 in their comments
# and carry the 2024-03-01 number in the attribute — Qualcomm edited the value
# and not the header. Taking the number as authoritative is deliberate: it is
# what PackageManager reads, and it is what the device advertised before this
# change.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.opengles.aep.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.opengles.aep.xml \
    frameworks/native/data/etc/android.hardware.vulkan.compute-0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.compute-0.xml \
    frameworks/native/data/etc/android.hardware.vulkan.level-1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.level-1.xml \
    frameworks/native/data/etc/android.hardware.vulkan.version-1_1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.version-1_1.xml \
    frameworks/native/data/etc/android.hardware.vulkan.version-1_3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.version-1_3.xml \
    frameworks/native/data/etc/android.software.opengles.deqp.level-2024-03-01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.opengles.deqp.level.xml \
    frameworks/native/data/etc/android.software.vulkan.deqp.level-2024-03-01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.vulkan.deqp.level.xml

# Keystore / verified boot. ⚠️ android.software.device_id_attestation says the
# KeyMint TA can attest device identifiers; it does NOT claim key attestation
# with a real OEM root, which this port can never have (unlocked bootloader).
# Both claims are stock's, and both are what the TA actually implements.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.keystore.app_attest_key.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.keystore.app_attest_key.xml \
    frameworks/native/data/etc/android.software.device_id_attestation.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.device_id_attestation.xml \
    frameworks/native/data/etc/android.software.verified_boot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.verified_boot.xml

# Input
# The Lenovo folio keyboard and touchpad both enumerate as 17ef:62b2 on bus
# 0x0019. The stylus digitizer (NVTCapacitivePen) needs no configuration at all:
# it sits on SPI with a zero VID/PID, so it matches no Vendor_*.idc, and AOSP
# classifies it as a STYLUS purely from its evdev capabilities
# (BTN_TOOL_PEN, BTN_STYLUS, BTN_STYLUS2, ABS_PRESSURE, ABS_TILT_X/Y).
#
# 17ef:617f is the *other* half of the pen: its Bluetooth HID side, which
# carries the side-button gestures. That is a different device from the SPI
# digitizer above and needs its own keylayout — without one the side button
# does nothing at all. DEVICE-FACTS.md has documented since session 1 that the
# stock system loads Vendor_17ef_Product_617f.kl for it, but the file was only
# ever staged under work/analysis/ and never wired in here. See the header of
# our keylayout for why the stock file cannot be copied verbatim (six Lenovo
# labels that KeyLayoutMap rejects, taking the whole file down with them) and
# why the stock .idc is deliberately not carried.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/keylayout/Vendor_17ef_Product_62b2.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_17ef_Product_62b2.kl \
    $(LOCAL_PATH)/keylayout/Vendor_17ef_Product_617f.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_17ef_Product_617f.kl \
    $(LOCAL_PATH)/idc/Vendor_17ef_Product_62b2.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/Vendor_17ef_Product_62b2.idc

# Device state — folio cover close-to-sleep / open-to-wake.
#
# DeviceStateProviderImpl.java:104-106,818-830 looks for this file at
# /data/system/devicestate/device_state_configuration.xml first and falls back
# to /vendor/etc/devicestate/, so the vendor path is the one to install to.
# Without the file the provider synthesises a single DEFAULT state and the
# sleep/wake plumbing in LogicalDisplayMapper never has two states to move
# between.
#
# The cover magnet is a sensor, not an input device — the file itself carries
# the full derivation, including how the polarity was measured rather than
# guessed. The paired resources are config_deviceStatesOnWhichToSleep and
# config_deviceStatesOnWhichToWakeUp in FrameworkOverlayMalbec.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/device_state_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/devicestate/device_state_configuration.xml

# QTI perf config store.
#
# The other thirteen files in vendor/etc/perf/ stay blobs and are byte identical
# to the factory ones. This one is owned here because it needs exactly one value
# changed and there is no runtime way to change it: memperfd is disabled,
# because the QHCP service it blocks on forever is registered by /vendor/bin/qms
# (the modem QMI daemon) which a Wi-Fi-only tablet does not ship. The full
# derivation and the live measurement are in the file's own comment.
#
# Keep this in sync when the factory firmware is updated: diff the new stock
# perfconfigstore.xml against this one and re-apply the single memperfd line.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml

# RRO partition precedence.
#
# ★ SESSION 23: GApps were added, so the mechanism this file exists for is now
# LIVE. It is still, measurably, changing nothing — and the difference between
# those two statements is the whole point of keeping the file.
#
# What is now live: vendor/gapps/overlay/GmsOverlay is a STATIC RRO
# (AndroidManifest.xml: isStatic="true" priority="1337") that lands on /product
# and targets `android` — the same target package as FrameworkOverlayMalbec,
# which is also static, on /vendor, at priority 1. So for the first time there
# is a real competitor.
#
# ⚠️ And priority 1337 vs 1 is NOT what decides it, which is the thing to know
# before reasoning about this again. OverlayConfig.java builds its list with the
# PARTITION loop on the outside (:158 sortPartitions, then :199-208 collecting
# each partition's static overlays and sorting THAT list with
# sStaticOverlayComparator). android:priority therefore only ranks static
# overlays against each other WITHIN one partition; across partitions the file
# below is the only lever. Measured on the pre-GMS build and consistent with
# this: `cmd overlay list android` prints in increasing priority and puts all
# four /product static RROs BEFORE /vendor/overlay/FrameworkOverlayMalbec.apk,
# i.e. ours wins — the reverse of AOSP's default order, which is exactly what
# this file buys.
#
# What is still inert: the two resource sets do not intersect. GmsOverlay sets
# 22 resources and every one of them names a Google package —
# config_defaultAssistant, config_systemSpeechRecognizer, config_systemWellbeing,
# config_persistentDataPackageName, config_defaultAccessibilityService, the two
# credential-provider arrays, and so on. Not one of this device's 71 resources
# is among them, and in particular config_defaultNightMode — the resource the
# whole original argument was about — is NOT set by MindTheGapps at all. The
# PixelConfigOverlay2021_GMS that started this story is a different package and
# is not what ships here.
#
# ⚠️ Verify after the first GMS boot rather than trusting the paragraph above:
#     cmd overlay list android          <- FrameworkOverlayMalbec must be LAST
#     cmd overlay lookup android android:integer/config_defaultNightMode  -> 1
#
# ── The session-21 text, kept because it is the reasoning that was refuted ──
#
# ⚠️ SESSION 21: on LineageOS this file is INERT, and it is kept only because it
# costs nothing and becomes load-bearing again the moment GApps are added. The
# reasoning it used to carry does not survive the move and is recorded here as
# refuted rather than deleted, because it is the obvious thing to re-derive.
#
# What it used to say: this tree's overlays are in /vendor/overlay, which AOSP
# orders BELOW /product/overlay, so every GMS overlay silently outranks ours —
# measured with `cmd overlay list android`, which prints in increasing priority
# and put android.overlay.malbec ahead of com.google.android.overlay.pixelconfig*.
# The case that surfaced it was config_defaultNightMode, which
# PixelConfigOverlay2021_GMS pins to 2 (dark).
#
# On this tree:
#   · there is no vendor/gms, vendor/google or vendor/partner_gms, and nothing
#     in this device's makefiles inherits GApps — PixelConfigOverlay2021_GMS
#     does not exist, so there is no /product RRO to lose to;
#   · the competing config_defaultNightMode=2 comes from
#     vendor/lineage/overlay/common/frameworks/base/core/res/res/values/config.xml:153,
#     which vendor/lineage/config/common.mk:277-279 adds to
#     PRODUCT_PACKAGE_OVERLAYS. That is a STATIC overlay compiled into
#     framework-res.apk, not an RRO — and an RRO beats the target APK's own
#     resource table on any partition. FrameworkOverlayMalbec's 1 wins with no
#     reordering at all;
#   · LineageOS's own product-partition RROs (DocumentsUIOverlay, Launcher3Overlay,
#     NetworkStackOverlay, PermissionControllerOverlay) target
#     com.android.{documentsui,launcher3,networkstack,permissioncontroller} —
#     none of them targets framework-res, so the intersection with this device's
#     71 resources is empty;
#   · LineageOS ships no partition_order.xml of its own, so nothing collides.
#
# OverlayConfig.java:76 still hardcodes the path to /product/overlay, which is
# why a device-tree file lands on the product partition, and the file's own
# format rules still apply (a typo makes it silently ignored).
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/partition_order.xml:$(TARGET_COPY_OUT_PRODUCT)/overlay/partition_order.xml

# Game-mode thermal policy, owned by this tree rather than extracted.
#
# thermal-engine-v2 reads it by path (init.qcom.rc:516 passes
# -c /vendor/etc/thermal-engine-malbec-${vendor.thermal.mode}.conf), so
# installing it here is indistinguishable from the blob at runtime. The other
# SIX profiles stay extracted; only this one is tuned, and it is plain-text
# INI, so keeping it in git is what makes each tuning step a readable diff
# instead of an opaque 2 KB binary change.
#
# ★ ⚠️ SESSION 21: five of those six were NOT being extracted, and the gap had
# teeth. Stock ships seven malbec profiles — normal, audio, camera, floating,
# game, off, skynet — and proprietary-files.txt carried only `normal`. The
# hazard is the ordering in init.qcom.rc:523-526, which does
#
#     stop thermal-engine
#     start thermal-switch-engine
#
# so setting vendor.thermal.mode to any of the five missing values would have
# left thermal-engine-v2 exiting with "No platform thermal config file" AND the
# fallback daemon already stopped — i.e. no userspace thermal mitigation at all.
# Latent only because init.malbec.rc sets nothing but `game` and `normal`, and
# every comment in this tree that said otherwise was inviting the trap.
#
# audio, camera, floating, off and skynet are now extracted verbatim: 6,927
# bytes in total for five plain-text INI files.
#
# ⚠️ The matching line for the GAME profile is deliberately absent from
# proprietary-files.txt, because this tree owns that one.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/thermal/thermal-engine-malbec-game.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-malbec-game.conf

# ⚠️ KeypressInvalid.ogg and Trusted.ogg used to be copied here. They are gone —
# on LineageOS the gap they filled does not exist, and the lines were exact
# duplicates of what the product already installs.
#
# The original reasoning was sound for the ROM it was written against: both
# files are named by AOSP code (frameworks/base/core/res/res/xml/audio_assets.xml
# :34 declares FX_KEYPRESS_INVALID; SettingsProvider defaults.xml:81 points
# def_trusted_sound at the absolute path /product/media/audio/ui/Trusted.ogg),
# and vendor/pixel/sounds/common/common-vendor.mk omitted them both.
#
# LineageOS does not use that file. vendor/lineage/config/common_mobile.mk:5
# inherits frameworks/base/data/sounds/AudioPackage14.mk, whose EFFECT_FILES
# (:15-16) contains KeypressInvalid and Trusted, and whose :29-30 expands to
# copy pairs that are string-identical to the two removed here.
# build/make/core/Makefile:142-144 dedupes identical pairs before the
# destination-collision check, so the duplication was completely silent — no
# warning, no product_copy_files_ignored.txt entry, nothing.
#
# Related, and worth knowing before assuming anything else about
# /product/media/audio: LineageOS deliberately skips AOSP's AllAudio.mk.
# build/make/target/product/full_base.mk:48-50 guards it with
# `ifeq ($(LINEAGE_BUILD),)`, and LINEAGE_BUILD is exported by
# vendor/lineage/build/envsetup.sh. The sound set comes from AudioPackage14.mk
# plus vendor/lineage/config/{aosp,lineage}_audio.mk instead.

# The sinc resampler's coefficient library.
#
# AudioResamplerSinc.cpp:104 does dlopen("libaudio-resampler.so") and dlsyms
# readResamplerCoefficients out of it; without the library the highest-quality
# resampler quietly falls back to its small built-in coefficient set. It is a
# plain AOSP module (frameworks/av/media/libaudioprocessing/audio-resampler),
# not a blob — it is simply not in any makefile this product inherits. AOSP puts
# it in generic_system.mk:71 and mainline_system.mk:71, neither of which is on
# this product's inheritance path, so it has never been built here.
PRODUCT_PACKAGES += \
    libaudio-resampler

# DisplayDeviceConfig — the auto-brightness debounce, and nothing else.
#
# Without this file the device runs auto-brightness with the debounce at -1,
# which AutomaticBrightnessController uses as an arithmetic offset rather than
# checking, so every lux sample is allowed to move the backlight. The two
# framework resources that look like the fix are NOT reachable without a
# DisplayDeviceConfig file — the loader that reads them only runs from
# initFromFile(). The file carries the full derivation.
#
# ⚠️ Named by PORT, not by display id. The id forms encode the panel model and
# this tablet ships two panel vendors; the port is the same for both. Every
# section the file omits keeps its config.xml value, which is why it is safe for
# it to be four lines long.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/displayconfig/display_port_147.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_port_147.xml

# Rootdir
# fstab.qcom is the one vendor config this port has to change, so the device
# tree owns it and proprietary-files.txt skips the stock copy.
#
# init.recovery.qcom.rc is the recovery-side counterpart. Recovery never mounts
# /vendor, so the stock init.target.rc -- which is what creates
# /dev/block/bootdevice on a normal boot -- is not read there. Without this
# module recovery has no bootdevice symlink (most of fstab.qcom then fails) and
# no USB, i.e. no `adb sideload` and no fastbootd, which is exactly the tooling
# needed to recover from a bad flash. See rootdir/Android.bp.
# init.malbec.rc re-enables active-stylus scanning in the touch controller.
# nvt_touch.ko sends {0x7B, 0x00} ("pen not supported") once at ~7.3 s and never
# undoes it; on ZUI the framework calls the Lenovo touchscreen HAL to undo it,
# and LineageOS has no client for that HAL. The rc file carries the full
# derivation, including the boot-log line that shows the driver doing it.
PRODUCT_PACKAGES += \
    fstab.qcom \
    init.malbec.rc \
    init.recovery.qcom.rc

# ★ Recovery graphics: the QTI backend, because the generic one does not work on
# this panel. OPEN-ISSUES #15 predicted this risk and left it untested; flash 1
# of session 22 confirmed it — recovery renders a plain GREY SCREEN.
#
# Diagnosed from recovery's own log rather than from the symptom, which is worth
# stating because "recovery is blank" has a dozen plausible causes and this is
# only one of them. `adb shell cat /tmp/recovery.log` from the running recovery
# (possible at all only because #33 gave recovery an authorised root adb):
#
#     Display Mode 0 resolution: 3504 x 2190 @ 60 FPS
#     Choosing display mode #0
#     Allocating buffer with resolution 3504 x 2190 pitch: 14080 bpp: 32
#     Failed to drmModeSetCrtc(67)
#     cannot open any framebuffer: No such file or directory
#
# and the kernel's side of the same instant:
#
#     [drm:dsi_display_prepare] *ERROR* DMS not supported on first frame
#     [drm:dsi_bridge_pre_enable] *ERROR* DSI display prepare failed, rc=-22
#
# So minui finds the connector, reads the mode and allocates the framebuffer
# correctly — 3504x2190 is exactly this panel — and then the LEGACY modeset call
# is rejected with EINVAL. graphics_drm.cpp:160 uses drmModeSetCrtc(), and
# Qualcomm's DSI bridge treats a full mode set on the first frame as a dynamic
# mode switch, which it does not support. MinuiBackendDrmQti drives the same
# hardware through the ATOMIC API instead — drmModeAtomicAddProperty over the
# SDE planes, with the topology and SPR blobs the driver expects — which is the
# path the vendor composer also takes.
#
# graphics.cpp:397-410 is the whole switch: the flag decides which of the two
# MinuiBackend subclasses `create_backend(GraphicsBackend::DRM)` returns.
# graphics_drm_qti.cpp is in libminui's srcs unconditionally (minui/Android.bp
# :37-44) and its object already builds today, so this changes selection only —
# no new sources, no new headers, no build risk.
#
# ⚠️ Verify it the same way it was diagnosed, not by looking at the screen: boot
# to recovery and re-read /tmp/recovery.log. `Failed to drmModeSetCrtc` and
# `cannot open any framebuffer` must both be GONE. A screen that still looks
# wrong with a clean log is a different bug.
$(call soong_config_set_bool,recovery,target_recovery_uses_qti_drm,true)

# ⚠️ The prebuilt_etc above only produces /vendor/etc/fstab.qcom, and that alone
# DOES NOT BOOT. At first-stage mount /vendor is precisely the partition not yet
# mounted, so fs_mgr's GetFstabPath()
# (system/core/fs_mgr/libfstab/fstab.cpp) can only read the ramdisk copy at that
# moment. Stock's vendor_boot ramdisk does carry
# first_stage_ramdisk/fstab.qcom; this tree previously installed neither location,
# so ReadDefaultFstab() failed and init panicked.
# There is no DT-fstab fallback either: /proc/device-tree/firmware/android/ does
# not exist on this device.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/rootdir/etc/fstab.qcom:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/first_stage_ramdisk/fstab.qcom

# Overlays
# Framework RRO. Values are measured from the stock ROM's dumpsys display, not
# copied from another device — see the comments in its config.xml.
#
# WifiOverlayMalbec is not optional decoration on a Wi-Fi-only tablet. LineageOS
# builds the AOSP ServiceWifiResources.apk, and its defaults answer "no" to most
# capability questions: config_wifi5ghzSupport, config_wifi6ghzSupport,
# config_wifiSoftap*, config_wifiSaeH2eSupported and MAC randomisation are all
# false out of the box. Stock supplies them from four vendor RROs that live on
# partitions this port replaces. See the overlay's AndroidManifest for why one
# overlay covers what stock does with four, and which stock values are
# deliberately left out because their RROs are gated on vendor.sku=sun.
#
# SettingsOverlayMalbec removes the refresh-rate picker. On this panel every rate
# above 120 Hz is measurably worse — it costs the stylus entirely AND halves the
# finger report rate, 360 Hz -> 185 Hz — so there is no setting to offer. The
# measurements and the trap in the "obvious" alternative are in its config.xml.
#
# SystemUIOverlayMalbec puts the Device mode tile in the DEFAULT Quick Settings
# panel, so it is reachable from inside a full-screen game without being dragged
# in from the edit screen first.
#
# ⚠️ It overrides ONE default-tile string, not both — this line said both until
# session 21, while the overlay's own comment already documented dropping the
# other. QSHost.java:45-46 picks between quick_settings_tiles_new_default and
# quick_settings_tiles_default on `QsInCompose`, which is not itself an aconfig
# flag but `QSComposeFragment.isEnabled || SceneContainerFlag.isEnabled`; the
# real flag is qs_ui_refactor_compose_fragment
# (frameworks/base/packages/SystemUI/aconfig/systemui.aconfig:930-934), ENABLED
# and READ_ONLY in the bp3a config that bp4a inherits. So only the `new_default`
# string is ever read, and overriding the other one produced an idmap warning
# per boot and nothing else.
#
# ⚠️ There is deliberately NO Launcher3 overlay here. Session 24 shipped one
# (LauncherOverlayMalbec) that pointed all eleven xml/default_workspace_* at an
# empty <favorites/>, to give an empty default home screen; session 25 removed it
# at the owner's direction — the home screen is now Launcher3's own default,
# which is the standard AOSP/LineageOS behaviour. The reason is maintenance, not
# taste: the override had to enumerate every grid Launcher3 ships, it failed OPEN
# (a renamed or added grid silently restores the icons with no build error), and
# it therefore needed a bespoke guard script to stay true. A preference that
# costs a check script and a per-release audit is not worth expressing in the
# device tree — the user can clear the home screen in two minutes. See
# OPEN-ISSUES.md #32a/#63.
#
# LineageSDKOverlayMalbec exists for one integer: this tablet has NO notification
# LED, and lineage-sdk defaults config_deviceLightCapabilities to 8
# (LIGHTS_PULSATING_LED). Left alone, LineageOS offers notification-light
# settings for hardware that is not there. Owner-confirmed — see the overlay's
# own comment for why the sysfs evidence pointed the other way.
PRODUCT_PACKAGES += \
    FrameworkOverlayMalbec \
    LineageSDKOverlayMalbec \
    SettingsOverlayMalbec \
    SettingsProviderOverlayMalbec \
    SystemUIOverlayMalbec \
    WifiOverlayMalbec

# ── LiveDisplay ─────────────────────────────────────────────────────────────
#
# New in session 21. LineageOS ships a display-tuning framework that PixelOS has
# no equivalent of, and this device can drive two thirds of it with hardware it
# already has and blobs it already extracts. Nothing here is a port; both
# services are upstream LineageOS code enabled by configuration.
#
# 1. The SDM half — Display modes (screen colour profiles) and Picture
#    adjustment (hue/saturation/intensity/contrast).
#
#    hardware/lineage/interfaces/livedisplay/aidl/sdm/ builds
#    vendor.lineage.livedisplay-service.sdm with both interfaces on by default
#    (Android.bp:39-52). Its ONLY runtime dependency is a dlopen of
#    libsdm-disp-vndapis.so (SDMController.cpp:47-49), which this tree already
#    extracts — proprietary-files.txt:1188.
#
#    ⚠️ That dlopen is the reason this needed checking rather than assuming.
#    proprietary-files.txt documents at length that this device's SDM stack is a
#    private Lenovo/Motorola fork whose vtables and symbol sets differ from the
#    public CAF sources, so "the library is present" does not imply "it exports
#    the API LiveDisplay calls". Measured against the extracted blob before
#    enabling — all six entry points the controller resolves are exported:
#
#        disp_api_init                     disp_api_get_num_display_modes
#        disp_api_get_active_display_mode  disp_api_set_active_display_mode
#        disp_api_get_global_pa_range      disp_api_set_global_pa
#
#    ⚠️⚠️ THE NEXT PARAGRAPH USED TO SAY THIS, AND IT IS FALSE. It is left here
#    because it is the exact reasoning that cost flash 1 of session 22 — a boot
#    that never completed — and the shape of the mistake is worth more than the
#    correction:
#
#        "Failure mode if a later firmware drops one: LoadFunction returns
#         nullptr and every call returns NO_INIT. The service stays up and the
#         feature reports nothing — it does not crash and it cannot wedge boot."
#
#    Both halves are wrong, and they are wrong in the two places that matter.
#
#    · It DOES crash. DisplayModes.cpp:22-24 and PictureAdjustment.cpp:22-25 each
#      call LOG(FATAL) from the CONSTRUCTOR when isReady() is false, and
#      service.cpp:26-28 constructs both before registering either. Measured on
#      the device:
#
#          Abort message: 'DisplayModes backend not ready, exiting.'
#          #03 DisplayModes::DisplayModes(shared_ptr<SDMController>)+388
#
#      isReady() is not "did the symbols resolve". It is
#      CheckFeatureVersion(FEATURE_VER_SW_SAVEMODES_API) == OK AND
#      getNumDisplayModes() > 0 — a RUNTIME answer from the blob. Six exported
#      symbols proved the ABI existed and proved nothing about the backend.
#
#    · It DOES wedge boot, and this is the general lesson. A HAL declared in the
#      VINTF manifest but never registered is not a missing feature, it is an
#      infinite wait: LineageOS's framework LiveDisplayService calls
#      waitForDeclaredService(), which has no timeout, on a system_server thread
#      running PHASE_BOOT_COMPLETED. Observed once a second, forever:
#
#          W libbinder.ServiceManagerCppClient: Waited one second for
#            vendor.lineage.livedisplay.IDisplayModes/default
#
#      The user-visible symptom is nothing like a display fault: the boot
#      animation plays, then Settings$FallbackHome sits on a black screen because
#      user 0 never finishes unlocking, and eventually ANRs. See OPEN-ISSUES #34.
#
#    ★ So the rule for this device tree is: DECLARING A HAL IS A PROMISE THAT IT
#    WILL REGISTER. A service whose readiness depends on a blob has to be
#    measured on the hardware, not inferred from its symbol table, and the VINTF
#    fragment has to be removed in the same change that disables the interface —
#    which is what soong_config enable_dm/enable_pa does (Android.bp:41-52 gates
#    the fragment and the -DENABLE_* flag off the same variable).
#
#    Measured on the hardware, flash 1:
#        DisplayModes        isReady() false  -> disabled below
#        PictureAdjustment   registers        -> kept
#        SunlightEnhancement registers        -> kept (see the sysfs half)
#
#    Sepolicy costs nothing here: the domain, the exec label and the
#    vndbinder/display_vendor_data_file grants are all in
#    device/lineage/sepolicy/qcom/, which BOARD_VENDOR_SEPOLICY_DIRS already
#    picks up through device/qcom/sepolicy_vndr/SEPolicy.mk.
#
# 2. The sysfs half — Outdoor mode (high brightness mode).
#
#    Measured on the running stock ROM:
#        /sys/class/backlight/panel0-backlight/hbm  exists, 0666, reads 0
#        echo 1 > hbm  -> reads back 1;  echo 0 -> reads back 0
#    i.e. it is a live control, not a stub.
#
#    ⚠️ SE_PATH is NOT optional on this device. SunlightEnhancement.cpp:26-56
#    probes /sys/class/graphics/fb0/hbm and a qcom,dsi-display-primary path when
#    SE_PATH is undefined, and this is a DRM-only device with neither — and the
#    constructor ends in LOG(FATAL) if nothing opens. Shipping the service
#    without se_path would abort it on every start.
#
#    The two services register disjoint interfaces (DM/PA vs SE), so they
#    coexist; nothing arbitrates between them.
PRODUCT_PACKAGES += \
    vendor.lineage.livedisplay-service.sdm \
    vendor.lineage.livedisplay-service.sysfs

# ★ Display modes OFF. Measured, not assumed — see the correction above.
# DisplayModes::isReady() needs FEATURE_VER_SW_SAVEMODES_API to report a non-zero
# version AND getNumDisplayModes() > 0; this blob fails that and the constructor
# calls LOG(FATAL). Turning the soong_config variable off does BOTH halves of the
# fix at once (Android.bp:41-52): it stops compiling DisplayModes into the binary
# (-DENABLE_DM=false) and it stops installing
# vendor.lineage.livedisplay-service.sdm-dm.xml, so nothing declares an interface
# that will never register. Either half alone leaves the boot hang in place.
#
# Picture adjustment stays on: with DM off the same binary comes up and registers
# IPictureAdjustment/default (verified with `service list` on the device), so this
# device gets hue/saturation/intensity/contrast and loses only colour profiles —
# which the hardware never supported.
$(call soong_config_set_bool,livedisplay_sdm,enable_dm,false)

$(call soong_config_set_bool,livedisplay_sysfs,enable_se,true)
$(call soong_config_set,livedisplay_sysfs,se_path,/sys/class/backlight/panel0-backlight/hbm)

# Charging control — "Charging optimisation" in Settings > Battery.
#
# Everything except the wiring already exists in this tree:
# hardware/lineage/interfaces/health/aidl/default/ChargingControl.cpp is a
# config-driven HAL, and packages/apps/Settings/src/com/android/settings/
# lineage/health/ChargingControlSettings.java is the UI. The domain, exec label
# and service_contexts entry come from device/lineage/sepolicy/common, which
# BOARD_VENDOR_SEPOLICY_DIRS already includes.
#
# Both LIMIT and TOGGLE are wired, and getting LIMIT to work took finding a gate
# that is not part of the LineageOS contract at all.
#
# LIMIT drives /sys/class/power_supply/battery/charge_control_{start,end}_threshold.
# Those two look writable (0644, root, no error on write) and are NOT, until
# /sys/class/qcom-battery/charge_control_en is 1 -- which it is not at boot.
# Measured on the running unit:
#
#     charge_control_en = 0 : writing 60, 70, 75, 90, 100 to end_threshold all
#                             leave it at 80; start_threshold stays at 70
#     charge_control_en = 1 : 85, 60, 95 all take; start 50 and 80 take
#
# qti_battery_charger.ko is where that comes from: battery_psy_set_charge_end_
# threshold only forwards to the charger firmware when the class attribute is
# set, and it range-checks. The driver prints its own bounds, so these are its
# numbers rather than ours:
#
#     end_threshold   [55 100]
#     start_threshold [50 95]
#
# Settings' slider is 70..100 (ChargingLimitPreference.java:50-51) and
# config_chargingControlBatteryRechargeMargin is 10, so Limit.java asks for
# max=<target>, min=<target-10>, i.e. 60..90 for start and 70..100 for stop.
# Every value the UI can produce is inside the driver's range.
#
# init.malbec.rc opens the gate and parks the pair at 100/95 -- no cap -- so
# nothing changes for someone who never turns the feature on. Without that
# parking the stock 70/80 would become live the moment the gate opened, and the
# tablet would quietly stop charging at 80%.
#
# TOGGLE stays wired alongside it on input_suspend, because the time-based modes
# ("charge to full by <time>") need to actually pause charging rather than set a
# ceiling. Measured: echo 1 -> status "Not charging" with usb/online still 1;
# echo 0 -> "Charging".
#
# supports_bypass is false because it is not true here: input_suspend cuts the
# charger input, so above the limit the tablet runs off its own battery rather
# than off the wall. That flag is what Toggle.java:91-93 uses to decide whether
# it must monitor the battery level, and claiming bypass we do not have would
# make it stop monitoring.
PRODUCT_PACKAGES += \
    vendor.lineage.health-service.default

$(call soong_config_set,lineage_health,charging_control_charging_path,/sys/class/power_supply/battery/input_suspend)
$(call soong_config_set,lineage_health,charging_control_charging_enabled,0)
$(call soong_config_set,lineage_health,charging_control_charging_disabled,1)
$(call soong_config_set_bool,lineage_health,charging_control_supports_bypass,false)
# ⚠️ LIMIT is deliberately NOT enabled, and the reason was only found after
# flashing. charge_control_en is a ONE-SHOT latch, not a persistent enable:
# measured on the flashed build,
#
#     echo 1 > charge_control_en        -> reads back 1
#     echo 90 > ..._end_threshold       -> takes; charge_control_en now reads 0
#     echo 100 > ..._end_threshold      -> IGNORED, stays 90
#
# i.e. the gate is consumed by the threshold write that follows it. The HAL
# (hardware/lineage/interfaces/health/aidl/default/ChargingControl.cpp:232-246)
# writes max then min and knows nothing about a gate, so every change the user
# makes in Settings after the first one would be silently dropped. Enabling
# LIMIT here ships a control that reports success and does nothing.
#
# TOGGLE on input_suspend has none of that problem and still gives the user the
# same feature: Toggle.java:237-239 advertises MODE_LIMIT, and with TOGGLE the
# framework watches the battery level itself and pauses charging at the target.
#
# To revisit: LIMIT would need ChargingControl.cpp to write the gate before each
# setChargingLimit(), i.e. this tree's first patch outside device/ and vendor/.
# The gain over TOGGLE is real but small (firmware enforces it, so it keeps
# working while the CPU is asleep) and it is the owner's call, not a bug fix.
$(call soong_config_set_bool,lineage_health,charging_control_supports_limit,false)

# Screen
# ⚠️ TARGET_SCREEN_HEIGHT/WIDTH moved to BoardConfig.mk in session 21, next to
# TARGET_SCREEN_DENSITY where every other LineageOS tree keeps all three.
#
# They worked here, but only by an ordering accident worth not depending on:
# vendor/lineage/config/common.mk:137-138 sets `TARGET_SCREEN_WIDTH ?= 1080`,
# and lineage_malbec.mk inherits device.mk AFTER common_full_tablet_wifionly.mk,
# so this file's `:=` happened to land second. Anything that reordered those two
# inherit-product lines would have silently given the boot animation generator a
# 1080-wide panel.

# WiFi
# Built from source, not carried as blobs — see the WiFi section of
# BoardConfig.mk for why. The per-device tuning files (WCNSS_qcom_cfg.ini for
# each chip directory, vendor_cmd.xml, the supplicant overlays and
# etc/hostapd/*) stay as blobs, since they are this board's configuration and
# do not exist in AOSP.
PRODUCT_PACKAGES += \
    android.hardware.wifi-service \
    hostapd \
    hostapd_cli \
    libwifi-hal-qcom \
    wpa_cli \
    wpa_supplicant \
    wpa_supplicant.conf

# ⚠️ BRING-UP ONLY — root shell on first boot, gated on MALBEC_BRINGUP.
#
# ⚠️ SESSION 21: the reason this block used to give is FALSE on LineageOS, and
# the property may well be unnecessary now. Kept for the first flash only, and
# to be re-tested on it.
#
# What it used to say: "`adb root` does NOT work on this ROM, because PixelOS
# patches init — SetSafetyNetProps() (system/core/init/property_service.cpp
# :1377-1389) hard-codes ro.debuggable=0 before bootconfig is parsed, and ro.* is
# write-once. PixelOS compensates by compiling adbd with ANDROID_DEBUGGABLE=1
# (packages/modules/adb/Android.bp:47-56)."
#
# Both halves are wrong here:
#   · `SetSafetyNetProps` does not exist anywhere in this tree. It was a PixelOS
#     init patch; LineageOS does not carry it, so on a LineageOS userdebug build
#     ro.debuggable=1 propagates normally and `adb root` should just work.
#   · The adbd citation is not a PixelOS patch either — Android.bp:47 defaults
#     `-DANDROID_DEBUGGABLE=0` and :49-56 flips it from the `debuggable` product
#     variable. That is stock AOSP.
#
# ★ TEST ON THE FIRST BOOT: `adb root && adb shell id`. If it returns uid=0, the
# whole block can go; delete it rather than leave a workaround for a problem this
# ROM does not have.
#
# The one reason that survives is the narrow one at the end of this comment: it
# avoids `ctl.restart adbd`. Read that before deciding.
#
# What actually gates root is packages/modules/adb/daemon/main.cpp:66-96:
#
#     bool ro_debuggable = ANDROID_DEBUGGABLE || __android_log_is_debuggable();
#     std::string prop = GetProperty("service.adb.root", "");
#     bool adb_root = (prop == "1");
#     if (ro_debuggable && adb_root) { drop = false; }
#
# The normal way to set that property is the Developer Options "Rooted debugging"
# toggle, which writes /data/adbroot/enabled -- fine once there is a UI, useless
# during a bring-up where the screen may never come up.
#
# Setting it here instead means adbd starts as root from the very first boot,
# and -- this is the part that matters -- WITHOUT an adbd restart. Running
# `adb root` on the looping first-flash build knocked the device off USB
# entirely: it issues `ctl.restart adbd`, and USB re-enumeration on this device
# goes through vendor.usbgadget-hal / usb_hal_service, both of which were in the
# crash cascade. The device had to be physically re-plugged.
#
# It goes in PRODUCT_SYSTEM_PROPERTIES rather than vendor.prop because
# service.adb.root is not in the vendor property namespace (it is labelled
# shell_prop in system/sepolicy/private/property_contexts:52), and vendor
# build.prop entries are namespace-checked at build time.
#
# MALBEC_BRINGUP is read from the environment here -- product config is parsed
# before BoardConfig.mk, so the `?=` default there is not visible yet.
# work/scripts/40-build.sh exports it; a bare `m` leaves it unset and gets no
# root, which is the correct default for anything shipped.
# Levels 0 and 1 get the root shell; level 2 (release) does not. `true` is still
# accepted as an alias for 0. See the level table in BoardConfig.mk.
#
# ⚠️ The filter has to list the aliases explicitly rather than reuse BoardConfig's
# normalisation: product config is parsed BEFORE BoardConfig.mk, so the `?=` and
# the true/false rewriting there are not visible here yet. An unset variable
# filters to nothing and gets no root, which is the correct default.
ifneq (,$(filter 0 1 true,$(MALBEC_BRINGUP)))
PRODUCT_SYSTEM_PROPERTIES += \
    service.adb.root=1
endif
