#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

LOCAL_PATH := device/lenovo/malbec

# Soong namespaces
# vendor/lenovo/malbec/Android.bp imports device/lenovo/malbec, so the namespace
# has to be declared here and made visible to the product.
PRODUCT_SOONG_NAMESPACES += \
    $(LOCAL_PATH)

# Proprietary blobs
$(call inherit-product, vendor/lenovo/malbec/malbec-vendor.mk)

# Symlinks that point at runtime locations instead of shipped files, so
# extract-utils cannot generate them. See Android.bp for what each one is for.
PRODUCT_PACKAGES += \
    malbec_wlanmdsp_otaupdate_symlink \
    malbec_wlan_cfg_kiwi_v2_symlink \
    malbec_wlan_cfg_peach_symlink \
    malbec_wlan_cfg_peach_v2_symlink \
    malbec_wlan_cfg_qca6750_symlink \
    malbec_wlan_cfg_wcn7750_symlink \
    malbec_wlan_mac_kiwi_v2_symlink \
    malbec_wlan_mac_peach_symlink \
    malbec_wlan_mac_peach_v2_symlink \
    malbec_wlan_mac_qca6750_symlink \
    malbec_wlan_mac_wcn7750_symlink \

# ⚠️ There used to be a CneApp.libvndfwk_detect_jni.qti_vendor_symlink here,
# working around an UnsatisfiedLinkError in CneApp. Session 13 removed CneApp
# itself along with the rest of the cellular stack: CNE is Qualcomm's
# Connectivity Engine, which arbitrates between cellular and Wi-Fi, and this is
# a Wi-Fi-only tablet (ro.baseband=apq, no RIL running, lshal reports zero
# radio/ims interfaces). With the app gone the symlink has nothing to satisfy.

# Generic ramdisk allow list
$(call inherit-product, $(SRC_TARGET_DIR)/product/generic_ramdisk.mk)

# Project ID Quota
$(call inherit-product, $(SRC_TARGET_DIR)/product/emulated_storage.mk)

# Virtual A/B
# Stock enables compression, userspace snapshots, batch writes, io_uring and
# XOR (ro.virtual_ab.compression.xor.enabled=true), so inherit the XOR variant.
# It chains through compression.mk to launch_with_vendor_ramdisk.mk, which is
# where PRODUCT_VIRTUAL_AB_OTA and the vendor ramdisk fsck tools come from.
$(call inherit-product, $(SRC_TARGET_DIR)/product/virtual_ab_ota/compression_with_xor.mk)

# Dalvik vm configs
# 6144 is the largest profile AOSP ships and is the right one for this 8 GB device.
# The "phone" in the name is historical; the profiles are keyed on RAM and density.
$(call inherit-product, frameworks/native/build/phone-xhdpi-6144-dalvik-heap.mk)

# AVF
# Stock ships com.android.virt, so keep parity. Note that VmTerminalApp is
# deliberately NOT included: the hypervisor here is Gunyah, not KVM, /dev/kvm
# does not exist and only protected VMs are supported, so the Terminal's
# non-protected Debian VM cannot start. See PROGRESS.md.
$(call inherit-product, packages/modules/Virtualization/apex/product_packages.mk)

# Qualcomm
# ⚠️ This line is a NO-OP and the story that used to be written here never
# happened. Kept only because it documents the correct intent; delete it if you
# would rather have one less lie in the file.
#
# The old comment claimed the previous value "modem_firmware" produced a dangling
# /vendor/rfs/msm/mpss/readonly/firmware symlink. It cannot have:
# hardware/qcom-caf/common/Android.bp:236-243 offers exactly two branches,
# "firmware" -> /firmware and "firmware_modem" -> /vendor/firmware-modem, with
# `default: "/vendor/firmware_mnt"`. Neither "modem_firmware" NOR "firmware_mnt"
# matches a branch, so both fall to the same default. Setting it changes nothing.
# Verified on the built image: all 84 vendor/rfs/** symlinks are byte-identical
# to the factory ones.
$(call soong_config_set,rfs,mpss_firmware_symlink_target,firmware_mnt)
$(call inherit-product, hardware/qcom-caf/common/common.mk)

# vndservicemanager must be built from source, not carried as a blob.
#
# This one has to be requested explicitly, and the reason is a trap worth
# spelling out. base_vendor.mk does list it -- but at :105-108, under
# PRODUCT_PACKAGES_SHIPPING_API_LEVEL_29, not PRODUCT_PACKAGES. main.mk:1005
# folds that list in only when math_gt_or_eq(29, PRODUCT_SHIPPING_API_LEVEL) is
# true, and this product ships 36 (see PRODUCT_SHIPPING_API_LEVEL below). So
# AOSP contributes nothing here: dropping the blob line WITHOUT this block would
# leave /vendor/bin/vndservicemanager missing entirely, and
# vendor/etc/selinux/vndservice_contexts (generated by system/sepolicy, not a
# blob) names 12 QTI services that must register on /dev/vndbinder --
# display.qservice, vendor.qcom.PeripheralManager, the gnss xtra service, the
# nwmgr service, wfd.native.mm.service and more.
#
# Why it cannot stay a blob: Lenovo's copy is an Android-15 build of
# android::ServiceManager, and /vendor/lib64/libbinder.so is built from this
# tree (Android 16). AOSP inserted getService2 and checkService2 into
# IServiceManager *before* addService, so every vtable slot from addService on
# is shifted by two. BnServiceManager::onTransact then calls the wrong virtual
# with the wrong argument types -- observed as both
# "Check failed: outList->empty()" in listServices and a null deref in
# IInterface::asBinder. Since Android 15 removed the VNDK, libbinder is compiled
# from the current tree into /vendor and its C++/AIDL ABI is explicitly
# unstable, so a vendor binary that *implements* an AOSP Bn* interface has to be
# rebuilt with the tree. vndservicemanager is the only blob on this device that
# does. Every symbol still resolved, so no link-time check could have caught it.
#
# This mattered more than a single dead service: vndservicemanager.rc carries
# "onrestart class_restart main / hal / early_hal" (byte-identical to AOSP's --
# Lenovo never touched the file), and it is the only .rc in all 138 vendor init
# files that cascades. One crash restarted the whole userspace every ~5 s, which
# is why the first flash never reached the launcher.
#
# vndservice and the .rc come along for free:
# frameworks/native/cmds/servicemanager/Android.bp:80-93 has
# required: ["vndservice"] and init_rc: ["vndservicemanager.rc"].
PRODUCT_PACKAGES += \
    vndservicemanager

# QTI HALs built from source rather than carried as blobs, matching onyx.
# The sources are in this tree (hardware/qcom-caf, vendor/qcom/opensource), so
# the stock binaries would only shadow them — and being compiled against an
# older AIDL version, the resulting module ends up depending on two versions of
# the same interface at once, which Soong rejects:
#
#   android.hardware.health-service.qti: depends on multiple versions of the
#   same aidl_interface: android.hardware.health-V3-ndk-source,
#   android.hardware.health-V4-ndk-source
#
# proprietary-files.txt excludes all of them.
# ⚠️ 这份名单曾经漏了一大半，而漏掉的方式很隐蔽，值得写下来：
# 生成 proprietary-files.txt 的分类器有一条规则是「模块名定义在启用的 QTI
# soong 命名空间里 -> 这个 blob 不用提取」。规则本身没错，错在它从没核对过
# 那个源码模块**是否真的进了 PRODUCT_PACKAGES**。定义 != 构建。
# 于是 composer / boot control / thermal / 音频 HAL 实现库两头落空：
# blob 删了、源码也没人装。没有 composer，SurfaceFlinger 起不来，设备是黑屏的。
# 现在由 work/scripts/24-blob-reconcile.py 做反向对账（出厂有、镜像里没有 =
# 缺口），这一类不会再无声无息地漏掉。
PRODUCT_PACKAGES += \
    android.hardware.health-service.qti \
    android.hardware.thermal-service.qti \
    android.hardware.usb-service.qti \
    android.hardware.usb.gadget-service.qti \
    audiohalservice.qti \
    vendor.qti.qspa-service

# Display: the whole QTI display stack is a BLOB. Do not move it back to source.
#
# ⚠️ 这一段以前写的是「整条显示栈本树都是从源码构建的…… blob 一个都没有，
# 所以 composer 必须跟着从源码走」。**那个前提是假的**，而且它让第十一轮把
# 正确答案当成「已排除」，白花了一整轮：
#
#   · libsdmextension.so（2.3 MB）一直就是 blob，而且是耦合最紧的那一个。
#     它是 dlopen 进来的（core_impl.cpp:80），**不在任何 DT_NEEDED 里**，
#     所以按链接图找不到它 —— 这就是当初漏看的原因。
#   · OPEN-ISSUES #9 的「排除项 3」说 onyx 同样从源码构建这套显示栈。
#     实测 onyx 把**整簇**当 blob：proprietary-files.txt:2261,2274-2296,2320，
#     device.mk:130-143 只装外围模块。
#
# 出厂的 SDM 是 Lenovo/Motorola 私有分支（SetMotoColor / SetRGBASplit /
# SetMotoPAHsic，公开 CAF 源码里 0 命中），sdm::DisplayBase 的虚表比本树源码
# **多 2 个槽**（161 vs 159），数据成员多 48 字节。分支源码不公开，
# libsdmextension 也没有源码 —— **从源码构建这一半在结构上就不可能正确**。
# 完整判据与实测数据写在 proprietary-files.txt 的 Display 段。
#
# 出厂 ROM 就是存在性证明：出厂指纹 TB390FU:16/... 是 Android 16 框架 +
# 202404 冻结的 vendor，与本树同一个 Treble 配置。
#
# 出厂 composer 二进制链 vendor.qti.hardware.display.composer3-V1-ndk.so，
# 而本树默认只装 V3 —— 这是那 28 个文件的 DT_NEEDED 闭包唯一缺的一个库（实测）。
#
# 补法看着简单，实际有两条死路，两条都实测撞过，写下来省得再走一遍：
#
#   ✗ 直接 `PRODUCT_PACKAGES += vendor.qti.hardware.display.composer3-V1-ndk`
#     soong bootstrap 失败。commonsys-intf/display/aidl/composer3/Android.bp:22-25
#     的 versions_with_info 里版本 1 import 的是 android.hardware.graphics.
#     composer3-**V4**，而 composer blob 自己直接链 composer3-**V3**-ndk.so ——
#     同一个 aidl_interface 的两个版本进了同一张依赖图，Soong 拒绝。
#     （出厂那份 V1 是照 V3 编的：readelf -d 它，NEEDED 里就是 composer3-V3-ndk。
#      树里 V1→V4 这个 import 是上游后来改的，与出厂二进制对不上。）
#
#   ✗ 把出厂的 .so 提取成 blob（含 ;MODULE_SUFFIX=_vendor）
#     ninja: multiple rules generate .../symbols/vendor/lib64/
#     vendor.qti.hardware.display.composer3-V1-ndk.so。改模块名躲不开：
#     ;MODULE_SUFFIX 只改**模块名**，stem 不变，所以安装路径还是同一个；
#     而源码那个 aidl 模块**本来就有**一条指向该路径的 install 规则
#     （只是没进 PRODUCT_PACKAGES 所以以前没装进镜像，ninja 的 dupbuild 检查
#      看的是规则不是打包结果）。这正是 proprietary-files.txt 里那句
#     「改名只有在树不往那个路径装东西时才成立」的反例。
#
# 正解是两步：composer blob 打 ;DISABLE_DEPS 切断它那条 aidl 依赖边（冲突就没了），
# 然后显式装源码构建的 V1 vendor 变体。`.vendor` 后缀是安装 vendor_available
# 模块的 vendor 变体的正确写法，QTI 自己在
# commonsys-intf/display/config/display-interfaces-product.mk:40-43 就是这么写的。
#
# ⚠️ `;DISABLE_DEPS` turns off shared_libs generation AND check_elf_file, so the
# build goes green while the image is missing libraries — the exact failure mode
# OPEN-ISSUES #3 documents. The safety net is work/scripts/33-blob-linkcheck.py,
# and it earned its keep here: with only V1 listed it reported
#
#   [vendor] android.hardware.graphics.composer3-V3-ndk.so   整个产物里都没有
#   [vendor] vendor.qti.hardware.display.aiqe-V2-ndk.so      整个产物里都没有
#   vendor/bin/hw/vendor.qti.hardware.display.composer-service  6 个符号解析不了
#
# Both had been installed only as a side effect of the SOURCE composer depending
# on them; dropping it took them with it. Run 33 after ANY ;DISABLE_DEPS change.
PRODUCT_PACKAGES += \
    vendor.qti.hardware.display.composer3-V1-ndk.vendor \
    vendor.qti.hardware.display.aiqe-V2-ndk.vendor \
    android.hardware.graphics.composer3-V3-ndk.vendor

# ⚠️ libgpu_tonemapper is the ONE member of the display cluster that stays on
# SOURCE, and it must. Blobbing it re-introduced the very bug that got the XR
# stack deleted:
#
#   work/scripts/37-layout-skew.py
#     ✗ vendor/lib64/libgpu_tonemapper.so: android::GraphicBuffer 分配 256 < A16 3376
#
# The factory copy is an Android-15 build that does operator new(256) for a class
# A16 grew to 3376 bytes (frameworks/native df868baf2a added mDependencyMonitor).
# It is reached whenever HDR tone mapping runs, so it would corrupt the heap in
# normal use, not in some corner.
#
# Source is safe for this one specifically, and the criterion is not a guess:
# the full exported-symbol-set diff of every source-built vendor library against
# its factory counterpart found the Moto fork in exactly five libraries —
# libsdmcore, libsdmclient, libsdmdal, snapalloc-impl, libgrallocutils.
# libgpu_tonemapper has ZERO factory-only symbols, i.e. it is not forked, so the
# tree build and the factory build are the same code.
#
# Nothing pulls it in automatically any more: the composer that used to depend on
# it is now a blob carrying ;DISABLE_DEPS, so it has to be named here.
PRODUCT_PACKAGES += \
    libgpu_tonemapper

# Audio HAL 实现库 —— 从源码构建。
# audiohalservice.qti 是个壳，真正的实现是它 dlopen 的这三个 .so。dlopen 不产生
# 构建依赖，所以必须显式列出来，否则服务起来了也没有 HAL。它们的 required: 会
# 带上 manifest_audiocorehal_default.xml / audioeffectservice_qti.xml 两个 VINTF
# 片段 —— 没有那两个，framework 的 FactoryHal 靠 AServiceManager_isDeclared 找
# HAL，会认为设备根本没有音频 HAL。
#
# ⚠️ 必须在这里显式钉死走源码还是走 blob，不能交给收敛循环去发现。
# 两条路各自自洽，但混在一起会来回震荡：blob 生成的 malbec-vendor.mk 会把
# libaudiocorehal.default 放进 PRODUCT_PACKAGES，不改名时这个名字解析到树内
# 源码模块，于是树装了这个路径、判据就认为 blob 多余把它删掉；删掉之后又没人
# 提供，下一轮再放回来。实测来回了三轮。
#
# ⚠️ 上一版在这里选了「从源码构建」，理由是出厂那三个 .so 的 DT_NEEDED 同时链了
# 同一个 AIDL 接口的多个版本，replace_needed 改不动。那个观察是对的，结论是错的
# —— 正解是 ;DISABLE_DEPS 加并装旧版接口，onyx 就是这么做的。走源码有两个它没看
# 到的代价：
#
#   1. 丢掉 Awinic 智能功放。出厂 libar-pal.so 导出 44 个 aw_ar_dsp_* /
#      aw_ar_kmsg_* / aw_audioreach_* 符号，CAF 源码里 awinic 相关代码是 0。
#      本机的功放就是它：设备上 aw882xx_dlkm 已加载（refcount 4），而本树还在发
#      校准数据 vendor/firmware/aw882xx_acf.bin 和校准工具 vendor/bin/aw882xx_cali
#      —— 数据和工具都在，消费它们的 API 没了。丢的不只是音质：excursion 和温度
#      保护也在这套 API 里。
#      把这个检查推广到全部 330 个「本树从源码构建且出厂也有」的库，扫 OEM 补丁
#      特征符号，只有 libar-pal.so 中招 —— 所以只有音频要回退，显示栈是干净的。
#
#   2. 它根本编不过。hardware/qcom-caf/sm8750/audio/pal 在本树里有 8 个 .o 因为
#      -Wformat 报错（Bluetooth.cpp、ResourceManager.cpp、SessionAlsa*.cpp、
#      SoundTriggerEngineGsl.cpp、StreamHaptics.cpp、HapticsDevProtection.cpp）。
#      m nothing 看不到这一层，上一轮的 mka bacon 在 9% 就死了，还没走到这里。
#
# 所以 PAL / AGM / graphservices / 三个 HAL 实现库 / st-hal 全部回到 blob，由
# proprietary-files.txt 按「树不装这个路径」自动纳入，冲突用 ;DISABLE_DEPS 处理
# （见 work/scripts/12-gen-proprietary-files.py 的 ENTRY_TAGS）。
#
# audiohalservice.qti 留在源码：它只是个壳，dlopen 那三个实现库，不链 PAL，实测
# 编得过，而且它的 init_rc: 会带出 vendor/etc/init/audiohalservice_qti.rc。
# libsoundtriggerhal.qti 则必须走 blob —— st-hal-ar/Android.bp:37 明确链 libar-pal。
# onyx 的分法完全相同。

# ★★ 这一条不装的话，机器**开不到 Launcher** ★★
#
# `properties/system_ext.prop:16` 设了 `ro.audio.ihaladaptervendorextension_enabled=true`
# （理由写在那里，是对的），但**实现服务一直没装**。属性设了、实现没有 ——
# 又是「声明了但没实现」那一类，而这一类在音频上是**致命**的，不是功能缺失：
#
#   frameworks/av/media/libaudiohal/impl/DevicesFactoryHalAidl.cpp:123-136
#     if (property_get_bool("ro.audio.ihaladaptervendorextension_enabled", false)) {
#         ... AServiceManager_waitForService(".../IHalAdapterVendorExtension/default")
#     } else { mVendorExt = nullptr; }
#
#   `waitForService` 是**无限等**的。于是实测的调用链是：
#     audioserver: AudioPolicyService::onFirstRef -> createAudioPolicyManager
#       -> AudioFlinger::getAudioPolicyConfig -> loadHwModule_ll
#       -> DeviceHalAidl::initCheck -> parseAndGetVendorParameters
#       -> HalAdapterVendorExtensionWrapper::getService -> 卡死
#   audioserver 因此永远不注册 IAudioFlingerService，而 system_server 在
#     AudioService.<init> -> readUserRestrictions -> setMicrophoneMuteNoCallerCheck
#     -> AudioSystem::isMicrophoneMuted -> getService<IAudioFlingerService>
#   上同样无限等 —— `sys.boot_completed` 永远不出现，开机动画一直转。
#   servicemanager 每秒打一次 "could not be found trying to start it as a lazy
#   AIDL service ... but was unable to"，那是症状不是原因。
#
# 这个服务本树自己就构建（vendor/qcom/opensource/commonsys/audio/hal_adapter/），
# 它的 .rc 带 `interface aidl android.media.audio.IHalAdapterVendorExtension/default`
# —— 正是这一行让 servicemanager 的 lazy start 能把它拉起来。
# 出厂镜像只发了 system_ext/lib64/libaudiohalvendorextn.so，**二进制和 .rc 都没发**
# （`ls system_ext/bin` 29 个文件里没有它），所以别拿出厂当参照。
# onyx 是对的：`device.mk:70` 装这个服务，`properties/system_ext.prop:2` 设那个属性
# —— 两个必须成对。
PRODUCT_PACKAGES += \
    qtiaudiohalvendorextn

# ★★ 承重，别精简 ★★
# 这一段和下面 199 行开始的那一段，是 `;DISABLE_DEPS` 的**补偿**。
# `;DISABLE_DEPS` 关掉的是 Soong 的依赖生成，也就是说：这些库 Soong **不会替我们
# 装**，也**不会报错**。删掉其中任何一行的后果是开机后 dlopen 失败，而 `m nothing`、
# `m pixelos`、check_elf_file 全都不会有任何反应 —— 构建期完全看不见。
# 判定这一整套是否还完整，用 `python3 work/scripts/33-blob-linkcheck.py`
# （它按链接器命名空间求解，不是按分区求并集）。
#
# ;DISABLE_DEPS 让 blob 不进 Soong 的依赖图，但运行时它们仍然要在 /vendor/lib64
# 里找到自己链的那个接口版本。本树解析到的是更新的版本，所以旧版必须显式并装。
# 版本号来自对出厂二进制逐个 readelf -d 的结果，不是猜的。
# 多版本共存本来就是支持的，本树已经有先例：android.media.audio.common.types
# 的 V2 和 V4 现在就同时装着。
PRODUCT_PACKAGES += \
    android.hardware.audio.common-V3-ndk.vendor \
    android.hardware.audio.core-V2-ndk.vendor \
    android.hardware.audio.core.sounddose-V1-ndk.vendor \
    android.hardware.audio.core.sounddose-V2-ndk.vendor \
    android.hardware.audio.effect-V2-ndk.vendor \
    android.hardware.bluetooth.audio-V3-ndk.vendor \
    android.hardware.bluetooth.audio-V4-ndk.vendor \
    android.hardware.drm-V1-ndk.vendor \
    android.hardware.health-V1-ndk.vendor \
    android.media.audio.common.types-V3-ndk.vendor \
    vendor.qti.hardware.paleventnotifier-V2-ndk.vendor

# 出厂音频 blob 依赖的 AOSP 支撑库的 vendor 变体。onyx 列的是同一批。
PRODUCT_PACKAGES += \
    libalsautilsv2.vendor \
    libaudioaidlcommon.vendor \
    libmediautils_vendor.vendor \
    libmemunreachable.vendor \
    libaudioutils_shim

# Dolby Atmos 的设置界面。
#
# 这台机器的 Dolby vendor 侧本来就**已经全在树里**了，只差一个前端：
#   vendor/bin/hw/vendor.dolby.dms.service          DMS HAL
#   vendor/lib64/vendor.dolby.dms-V1-ndk.so         它的 AIDL
#   vendor/lib64/soundfx/libswdapaidl.so            全局混音效果实现
#   vendor/etc/dolby/dax-default.xml                调音参数
#   vendor/etc/audio/sku_tuna/audio_effects_config.xml:21,78
#       <library name="dap" path="libswdapaidl.so"/>
#       <effect name="dap" uuid="9d4921da-8225-4f29-aefa-39537a04bcaa" .../>
# 也就是说效果一直在跑，只是**没有任何 UI 能调它**，所有参数停在默认值。
#
# 前端用 PixelOS 自己的 packages/apps/DolbyAtmos（co.aospa.dolby），不从出厂搬。
# 逐项核对过它确实是同一个东西，不是"看起来像"：
#   - 效果 UUID 9d4921da-8225-4f29-aefa-39537a04bcaa 与上面那份 config 逐字符相同
#   - 参数常量（CPDP_VALUES=5 / PROFILE=0xA000000 / SET_PROFILE_PARAMETER=0x1000000）
#     和 DsParam ID（101–116）与出厂 daxService 反编译出来的完全一致
#   - 20 段 GEQ 的频点表一致
#
# 为什么不搬 ZUI 那份：出厂的 Dolby 设置页**不在** daxService.apk 里
# （那个 APK 的 manifest 只有一个 bound service，没有任何设置 Activity），
# 而是 Lenovo 写在 ZuiSettings.apk 的 com.lenovo.settings.sound.dolby.*，
# 用的是 zui.appcompat.preference.SwitchPreference —— ZUI 私有控件，搬不过来，
# 硬搬也只会是机主明确否掉的"突兀插入"。而 PixelOS 这份是 Material 3 Expressive，
# 走 com.android.settings.category.ia.sound 注入，不需要动 Settings 源码，
# 功能上还是超集（11 项 vs 出厂 4 项，多出扬声器/耳机虚拟化、低音增强、
# 音量均衡、IEQ 预设、自定义 EQ 预设和一个快捷设置磁贴）。
#
# ⚠️ 不要**同时**装出厂的 daxService：两者都往同一个 global-mix 效果写 profile
# 参数，而 daxService 是 persistent=true，会互相打架。
PRODUCT_PACKAGES += \
    DolbyAtmos

# Miracast: the compat shim that gives libwfdnative.so the pre-Android-16
# MotionEvent::initialize symbol. See the blob_fixup in extract-files.py for why
# this is the correct fix rather than ;DISABLE_CHECKELF. Installs to
# /system_ext/lib64, the same namespace as its consumer.
PRODUCT_PACKAGES += \
    libinput_shim

# ── 带 ;DISABLE_DEPS 的 blob 所需、但全树无人提供的 soname ─────────────────
#
# 这一整类构建期是**查不出来**的：`;DISABLE_DEPS` 同时关掉 shared_libs 生成和
# check_elf_file，于是 Soong 既不去构建这个依赖也不报错，`m nothing` 和
# `m pixelos` 全绿，开机后 dlopen 失败。
#
# 第七个 session 用一次完整扫描定位（3370 个 ELF / 27346 条 DT_NEEDED，按**链接器
# 命名空间**求解而不是按分区求并集），实测 20 个真缺口。其中 7 个是新的一类：
# **文件在镜像里，但跨不过 vendor/system 命名空间边界** —— Android 16 没有 VNDK，
# /vendor 的二进制只看得到 /odm/lib64、/vendor/lib64{,/hw,/egl} 加上
# system/etc/llndk.libraries.txt 里那 26 个。所以 android.hardware.health@1.0.so
# 之类「/system/lib64 里明明有」的库，对 vendor 消费者等于不存在，必须装 .vendor 变体。
#
# 分法（判据是**谁在消费**，不是这个库长什么样）：
#   · 冻结的稳定接口（HIDL @x.y / AIDL -Vn-ndk）-> 走树。ABI 由冻结的接口定义，
#     树的构建与出厂逐符号等价，这一批已逐个对过消费者的未定义符号与提供者导出。
#   · 不是接口的普通 C++ 库、而消费者是出厂 blob -> 走 blob（在 proprietary-files.txt
#     里），因为那是 Android 15 的二进制，跨一个大版本的内部 ABI 不保证。
#     libaudioserviceexampleimpl / libaudioplatformconverter.qti / libnbaio_mono /
#     qti-audio-types-aidl-V1-ndk / 六个 soundfx AIDL 效果库都属于这一类。
PRODUCT_PACKAGES += \
    android.hardware.bluetooth.audio@2.0.vendor \
    android.hardware.bluetooth.audio@2.1.vendor \
    android.hardware.health@1.0.vendor \
    android.hardware.health@2.0.vendor \
    android.hardware.health@2.1.vendor \
    android.hardware.power@1.0.vendor \
    android.hardware.power@1.1.vendor \
    android.hardware.power@1.2.vendor \
    android.hardware.soundtrigger3-V1-ndk.vendor \
    android.hardware.thermal@1.0.vendor \
    android.hardware.thermal@2.0.vendor \
    android.media.soundtrigger.types-V1-ndk.vendor \
    com.dsi.ant@1.0.vendor \
    libaudio_aidl_conversion_common_ndk.vendor \
    libflatbuffers-cpp.vendor \
    libusbhost.vendor \
    libwfdaac_vendor \
    qti-audio-types-aidl-V1-ndk.vendor \
    vendor.qti.hardware.bluetooth.audio-V1-ndk.vendor \
    vendor.qti.hardware.display.allocator@4.0.vendor

# 这两个 VINTF 片段走源码而不是 blob。它们本来是 libaudiocorehal.default /
# libaudioeffecthal.qti 的 required:，实现库改回 blob 之后就没人带它们了，而出厂
# 那份提取出来会与源码那份重名（都是有名字的 prebuilt_etc，且
# ;MODULE_SUFFIX= 对 prebuilt_etc 静默无效）：
#   module "audioeffectservice_qti.xml": found in multiple
#   namespaces(hardware/qcom-caf/sm8750 and vendor/lenovo/malbec)
# 两份内容逐字段比对过，声明完全一致，只有注释不同，所以用哪份都行 ——
# 用源码那份可以避开命名冲突。
PRODUCT_PACKAGES += \
    manifest_audiocorehal_default.xml \
    audioeffectservice_qti.xml

# libaudioeffecthal.qti is built from source rather than extracted, and this is
# a deliberate exception to the "audio implementation libraries are blobs" rule
# two blocks up. That rule exists because the factory libar-pal.so carries 44
# Awinic smart-PA symbols the source tree has none of -- which is about
# libar-pal and libaudiocorehal, not about the effects library.
#
# The factory libaudioeffecthal.qti.so cannot be used on Android 16 at all. It
# memsets exactly 0x308 (776) bytes of stack and constructs a
# tinyxml2::XMLDocument there, but AOSP's tinyxml2 11.0.0 uprev grew that object
# to 0x370 (880). The extra 104 bytes land on the callee-saved register area and
# zero the TPIDR_EL0 copy used for the stack guard, so the next instruction
# (ldr x8,[x22,#0x28]) faults on address 0x28 -- esr 0x92000005, exactly what
# the first-flash tombstone shows. Every attempt to ship the 776-byte library
# instead is blocked by Android 16; the three measured refusals are documented
# at the top of proprietary-files.txt.
#
# The source build is compiled against the v11 header, so it reserves the right
# size and the bug cannot occur.
PRODUCT_PACKAGES += \
    libaudioeffecthal.qti

# IPA（数据路径加速）
#
# 两个配置文件必须显式列出来。ipacm 的 Android.bp 没有 required: 带上它们，
# 而「模块定义了」≠「本产品会构建」—— 这条教训 PROGRESS 第三节记过。
# 上一次完整构建装了 /vendor/bin/ipacm 却没有任何 IPACM_*.xml，
# 而 ipacm.rc:42 会 `copy /vendor/etc/IPACM_Filter_cfg.xml`。
#
# ⚠️ 走树而不是提取出厂那两份，理由是实测出来的：出厂的 IPACM_cfg.xml **没有**
# wlan0/wlan1/wlan2/wlan3/wigig0 这几个 Iface 条目，树里 sm8750 那份有
# （25 行差异全在这里）。这是一台 **WiFi-only** 平板，IPA offload 要用的恰恰
# 是 wlan 接口 —— 出厂那份是 Lenovo 按自己的 SKU 裁过的。
# IPACM_Filter_cfg.xml 两边逐字节相同，跟着走树保持一对。
# 而且 ipacm 二进制本身就是从 hardware/qcom-caf/sm8750 编的，配置跟二进制同源。
PRODUCT_PACKAGES += \
    ipacm \
    IPACM_cfg.xml \
    IPACM_Filter_cfg.xml

# Sensors
# The multihal service and its NDK bridge are AOSP's; only the sub-HALs listed
# in the stock /vendor/etc/sensors/hals.conf are device specific, and those stay
# as blobs. onyx does the same — it extracts no sensors service blob at all.
PRODUCT_PACKAGES += \
    android.hardware.sensors-service.multihal \
    sensors.dynamic_sensor_hal

# DRM
# clearkey is AOSP's reference plugin, not a device blob.
PRODUCT_PACKAGES += \
    android.hardware.drm-service.clearkey

# Device characteristics
# Not set anywhere in the inherited tablet config, but stock reports
# ro.build.characteristics=tablet and resource selection depends on it.
PRODUCT_CHARACTERISTICS := tablet

# Partitions
# BoardConfig.mk describes the super partition and its group, but the product
# side has to opt in as well: PRODUCT_BUILD_SUPER_PARTITION defaults to this, and
# without it no super.img is assembled.
PRODUCT_USE_DYNAMIC_PARTITIONS := true

# fstab.qcom mounts /vendor/firmware_mnt, /vendor/dsp and /vendor/bt_firmware.
# Stock ships those three as empty directories and proprietary-files.txt cannot
# carry an empty directory, so nothing would create them and all three mounts
# would fail. These modules exist for exactly that
# (hardware/qcom-caf/common/Android.bp); onyx pulls in the same set.
PRODUCT_PACKAGES += \
    vendor_bt_firmware_mountpoint \
    vendor_dsp_mountpoint \
    vendor_firmware_mnt_mountpoint

# A/B
# AB_OTA_UPDATER is set in BoardConfig.mk, but the updater itself is a product
# package. Without these three the build still produces an OTA zip and the device
# has nothing able to apply it.
#
# android.hardware.boot-service.qti 同样是必需的，而且比上面三个更早出问题：
# update_engine 拿不到 IBootControl 就无法把当前 slot 标记成 successful，
# bootloader 的重试计数耗尽后会回滚到另一个 slot。
# `android.hardware.boot` 在 compatibility_matrix.202404.xml 里没有
# optional="true"，是强制项。recovery 变体给 sideload 用。
PRODUCT_PACKAGES += \
    android.hardware.boot-service.qti \
    android.hardware.boot-service.qti.recovery \
    update_engine \
    update_engine_sideload \
    update_verifier

AB_OTA_POSTINSTALL_CONFIG += \
    RUN_POSTINSTALL_system=true \
    POSTINSTALL_PATH_system=system/bin/otapreopt_script \
    FILESYSTEM_TYPE_system=ext4 \
    POSTINSTALL_OPTIONAL_system=true

AB_OTA_POSTINSTALL_CONFIG += \
    RUN_POSTINSTALL_vendor=true \
    POSTINSTALL_PATH_vendor=bin/checkpoint_gc \
    FILESYSTEM_TYPE_vendor=ext4 \
    POSTINSTALL_OPTIONAL_vendor=true

PRODUCT_PACKAGES += \
    otapreopt_script \
    checkpoint_gc

# API
# Both values are what the device actually shipped with, read off the stock
# vendor build.prop: ro.board.first_api_level / ro.board.api_level = 202404 and
# ro.product.first_api_level = 36.
#
# BOARD_SHIPPING_API_LEVEL is the one that matters for booting. It is the vendor
# API surface this device froze at (Android 15, VINTF target-level 202404) while
# the framework side is Android 16, which is the Treble GRF arrangement this
# port depends on. Declare it too low or too high and the VINTF compatibility
# check between the framework matrix and the vendor manifest fails.
#
# PRODUCT_SHIPPING_API_LEVEL is 36 rather than onyx's 35 simply because this
# tablet launched on Android 16 and onyx launched on 15.
#
# BOARD_API_LEVEL is deliberately absent: the release config sets it from
# RELEASE_BOARD_API_LEVEL and build/make/core/board_config.mk errors out if a
# device tree assigns it.
BOARD_SHIPPING_API_LEVEL := 202404
PRODUCT_SHIPPING_API_LEVEL := 36

# Input
# The Lenovo folio keyboard and touchpad both enumerate as 17ef:62b2 on bus
# 0x0019. The stylus digitizer (NVTCapacitivePen) needs no configuration at all:
# it sits on SPI with a zero VID/PID, so it matches no Vendor_*.idc, and AOSP
# classifies it as a STYLUS purely from its evdev capabilities
# (BTN_TOOL_PEN, BTN_STYLUS, BTN_STYLUS2, ABS_PRESSURE, ABS_TILT_X/Y).
#
# 17ef:617f is the *other* half of the pen: its Bluetooth HID side, which
# carries the side-button gestures. That is a different device from the SPI
# digitizer above and needs its own keylayout — without one the side button
# does nothing at all. DEVICE-FACTS.md has documented since session 1 that the
# stock system loads Vendor_17ef_Product_617f.kl for it, but the file was only
# ever staged under work/analysis/ and never wired in here. See the header of
# our keylayout for why the stock file cannot be copied verbatim (six Lenovo
# labels that KeyLayoutMap rejects, taking the whole file down with them) and
# why the stock .idc is deliberately not carried.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/keylayout/Vendor_17ef_Product_62b2.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_17ef_Product_62b2.kl \
    $(LOCAL_PATH)/keylayout/Vendor_17ef_Product_617f.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_17ef_Product_617f.kl \
    $(LOCAL_PATH)/idc/Vendor_17ef_Product_62b2.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/Vendor_17ef_Product_62b2.idc

# Device state — folio cover close-to-sleep / open-to-wake.
#
# DeviceStateProviderImpl.java:104-106,818-830 looks for this file at
# /data/system/devicestate/device_state_configuration.xml first and falls back
# to /vendor/etc/devicestate/, so the vendor path is the one to install to.
# Without the file the provider synthesises a single DEFAULT state and the
# sleep/wake plumbing in LogicalDisplayMapper never has two states to move
# between.
#
# The cover magnet is a sensor, not an input device — the file itself carries
# the full derivation, including how the polarity was measured rather than
# guessed. The paired resources are config_deviceStatesOnWhichToSleep and
# config_deviceStatesOnWhichToWakeUp in FrameworkOverlayMalbec.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/device_state_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/devicestate/device_state_configuration.xml

# QTI perf config store.
#
# The other thirteen files in vendor/etc/perf/ stay blobs and are byte identical
# to the factory ones. This one is owned here because it needs exactly one value
# changed and there is no runtime way to change it: memperfd is disabled,
# because the QHCP service it blocks on forever is registered by /vendor/bin/qms
# (the modem QMI daemon) which a Wi-Fi-only tablet does not ship. The full
# derivation and the live measurement are in the file's own comment.
#
# Keep this in sync when the factory firmware is updated: diff the new stock
# perfconfigstore.xml against this one and re-apply the single memperfd line.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml

# RRO partition precedence.
#
# This tree's overlays are in /vendor/overlay, which AOSP orders BELOW
# /product/overlay - so every GMS overlay silently outranks ours. Measured, not
# assumed: `cmd overlay list android` prints in increasing priority and puts
# android.overlay.malbec first, ahead of com.google.android.overlay.pixelconfig*.
# The case that surfaced it is config_defaultNightMode, which
# PixelConfigOverlay2021_GMS pins to 2 (dark) - adding it to our overlay would
# simply have lost.
#
# OverlayConfig.java:76 hardcodes the path to /product/overlay, which is why a
# device-tree file lands on the product partition. The file itself carries the
# format rules (a typo makes it silently ignored) and the measurement showing our
# 71 resources and the product overlays' 595 currently have an EMPTY
# intersection, i.e. this reorder changes nothing else today.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/partition_order.xml:$(TARGET_COPY_OUT_PRODUCT)/overlay/partition_order.xml

# Rootdir
# fstab.qcom is the one vendor config this port has to change, so the device
# tree owns it and proprietary-files.txt skips the stock copy.
#
# init.recovery.qcom.rc is the recovery-side counterpart. Recovery never mounts
# /vendor, so the stock init.target.rc -- which is what creates
# /dev/block/bootdevice on a normal boot -- is not read there. Without this
# module recovery has no bootdevice symlink (most of fstab.qcom then fails) and
# no USB, i.e. no `adb sideload` and no fastbootd, which is exactly the tooling
# needed to recover from a bad flash. See rootdir/Android.bp.
# init.malbec.rc re-enables active-stylus scanning in the touch controller.
# nvt_touch.ko sends {0x7B, 0x00} ("pen not supported") once at ~7.3 s and never
# undoes it; on ZUI the framework calls the Lenovo touchscreen HAL to undo it,
# and PixelOS has no client for that HAL. The rc file carries the full
# derivation, including the boot-log line that shows the driver doing it.
PRODUCT_PACKAGES += \
    fstab.qcom \
    init.malbec.rc \
    init.recovery.qcom.rc

# ⚠️ 上面那个 prebuilt_etc 只产出 /vendor/etc/fstab.qcom，**开不了机**。
# 第一阶段挂载的时候 /vendor 正是还没挂上的那个分区，fs_mgr 的 GetFstabPath()
# （system/core/fs_mgr/libfstab/fstab.cpp）在这一刻只可能读到 ramdisk 里那份。
# 出厂的 vendor_boot ramdisk 里确实带着 first_stage_ramdisk/fstab.qcom，
# 而本树之前两个位置都没装 —— ReadDefaultFstab() 失败，init panic。
# 真机上 /proc/device-tree/firmware/android/ 不存在，所以也没有 DT fstab 那条退路。
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/rootdir/etc/fstab.qcom:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/first_stage_ramdisk/fstab.qcom

# Overlays
# Framework RRO. Values are measured from the stock ROM's dumpsys display, not
# copied from another device — see the comments in its config.xml.
#
# WifiOverlayMalbec is not optional decoration on a Wi-Fi-only tablet. PixelOS
# builds the AOSP ServiceWifiResources.apk, and its defaults answer "no" to most
# capability questions: config_wifi5ghzSupport, config_wifi6ghzSupport,
# config_wifiSoftap*, config_wifiSaeH2eSupported and MAC randomisation are all
# false out of the box. Stock supplies them from four vendor RROs that live on
# partitions this port replaces. See the overlay's AndroidManifest for why one
# overlay covers what stock does with four, and which stock values are
# deliberately left out because their RROs are gated on vendor.sku=sun.
#
# DolbyAtmosOverlayMalbec carries one array: the dialogue-enhancer step list,
# which upstream fills with a ladder this panel's Dolby tuning never uses, so
# the app showed "Unknown". Derived from vendor/etc/dolby/dax-default.xml —
# derivation in the overlay's own arrays.xml.
PRODUCT_PACKAGES += \
    DolbyAtmosOverlayMalbec \
    FrameworkOverlayMalbec \
    SettingsProviderOverlayMalbec \
    WifiOverlayMalbec

# Screen
TARGET_SCREEN_HEIGHT := 3504
TARGET_SCREEN_WIDTH := 2190

# WiFi
# Built from source, not carried as blobs — see the WiFi section of
# BoardConfig.mk for why. The per-device tuning files (WCNSS_qcom_cfg.ini for
# each chip directory, vendor_cmd.xml, the supplicant overlays and
# etc/hostapd/*) stay as blobs, since they are this board's configuration and
# do not exist in AOSP.
PRODUCT_PACKAGES += \
    android.hardware.wifi-service \
    hostapd \
    hostapd_cli \
    libwifi-hal-qcom \
    wpa_cli \
    wpa_supplicant \
    wpa_supplicant.conf

# ⚠️ BRING-UP ONLY — root shell on first boot, gated on MALBEC_BRINGUP.
#
# `adb root` does NOT work on this ROM, and the reason is not what the build
# script's comment used to say. PixelOS patches init: SetSafetyNetProps()
# (system/core/init/property_service.cpp:1377-1389) hard-codes ro.debuggable=0,
# ro.build.type=user and ro.build.tags=release-keys before bootconfig is even
# parsed, and ro.* is write-once, so the userdebug values from build.prop are
# silently rejected. That is deliberate upstream behaviour for app-facing root
# detection, and PixelOS patched the consumers to compensate: adbd is compiled
# with ANDROID_DEBUGGABLE=1 on userdebug (packages/modules/adb/Android.bp:47-56),
# so it ignores ro.debuggable entirely.
#
# What actually gates root is packages/modules/adb/daemon/main.cpp:66-96:
#
#     bool ro_debuggable = ANDROID_DEBUGGABLE || __android_log_is_debuggable();
#     std::string prop = GetProperty("service.adb.root", "");
#     bool adb_root = (prop == "1");
#     if (ro_debuggable && adb_root) { drop = false; }
#
# The normal way to set that property is the Developer Options "Rooted debugging"
# toggle, which writes /data/adbroot/enabled -- fine once there is a UI, useless
# during a bring-up where the screen may never come up.
#
# Setting it here instead means adbd starts as root from the very first boot,
# and -- this is the part that matters -- WITHOUT an adbd restart. Running
# `adb root` on the looping first-flash build knocked the device off USB
# entirely: it issues `ctl.restart adbd`, and USB re-enumeration on this device
# goes through vendor.usbgadget-hal / usb_hal_service, both of which were in the
# crash cascade. The device had to be physically re-plugged.
#
# It goes in PRODUCT_SYSTEM_PROPERTIES rather than vendor.prop because
# service.adb.root is not in the vendor property namespace (it is labelled
# shell_prop in system/sepolicy/private/property_contexts:52), and vendor
# build.prop entries are namespace-checked at build time.
#
# MALBEC_BRINGUP is read from the environment here -- product config is parsed
# before BoardConfig.mk, so the `?=` default there is not visible yet.
# work/scripts/40-build.sh exports it; a bare `m` leaves it unset and gets no
# root, which is the correct default for anything shipped.
ifeq ($(MALBEC_BRINGUP),true)
PRODUCT_SYSTEM_PROPERTIES += \
    service.adb.root=1
endif
